export const ACADEMY_REQUEST = "ACADEMY_REQUEST";
export const ACADEMY_SUCCESS = "ACADEMY_SUCCESS";
export const ACADEMY_FAIL = "ACADEMY_FAIL";

export const NEW_ACADEMY_REQUEST = "NEW_ACADEMY_REQUEST";
export const NEW_ACADEMY_SUCCESS = "NEW_ACADEMY_SUCCESS";
export const NEW_ACADEMY_RESET = "NEW_ACADEMY_RESET";
export const NEW_ACADEMY_FAIL = "NEW_ACADEMY_FAIL";

export const DETAIL_ACADEMY_REQUEST = "DETAIL_ACADEMY_REQUEST";
export const DETAIL_ACADEMY_SUCCESS = "DETAIL_ACADEMY_SUCCESS";
export const DETAIL_ACADEMY_FAIL = "DETAIL_ACADEMY_FAIL";

export const UPDATE_ACADEMY_REQUEST = "UPDATE_ACADEMY_REQUEST";
export const UPDATE_ACADEMY_SUCCESS = "UPDATE_ACADEMY_SUCCESS";
export const UPDATE_ACADEMY_RESET = "UPDATE_ACADEMY_RESET";
export const UPDATE_ACADEMY_FAIL = "UPDATE_ACADEMY_FAIL";

export const DELETE_ACADEMY_REQUEST = "DELETE_ACADEMY_REQUEST";
export const DELETE_ACADEMY_SUCCESS = "DELETE_ACADEMY_SUCCESS";
export const DELETE_ACADEMY_RESET = "DELETE_ACADEMY_RESET";
export const DELETE_ACADEMY_FAIL = "DELETE_ACADEMY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
