// DASHBOARD_PESERTA
export const GET_BOOKMARK_REQUEST = "GET_BOOKMARK_REQUEST";
export const GET_BOOKMARK_SUCCESS = "GET_BOOKMARK_SUCCESS";
export const GET_BOOKMARK_FAIL = "GET_BOOKMARK_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
