// DASHBOARD_PESERTA
export const GET_DASHBOARD_PESERTA_SUCCESS = "GET_DASHBOARD_PESERTA_SUCCESS";
export const GET_DASHBOARD_PESERTA_FAIL = "GET_DASHBOARD_PESERTA_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_SIMONAS_SUCCESS = "GET_SIMONAS_SUCCESS";
export const GET_SIMONAS_FAIL = "GET_SIMONAS_FAIL";

export const GET_BEASISWA_SUCCESS = "GET_BEASISWA_SUCCESS";
export const GET_BEASISWA_FAIL = "GET_BEASISWA_FAIL";
