// DASHBOARD_PESERTA
export const GET_DASHBOARD_PESERTA_SUCCESS = "GET_DASHBOARD_PESERTA_SUCCESS";
export const GET_DASHBOARD_PESERTA_FAIL = "GET_DASHBOARD_PESERTA_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
