//STORE TRAINING
export const STORE_TRAINING_STEP1 = "STORE_TRAINING_STEP1";
export const GET_TRAINING_STEP1 = "GET_TRAINING_STEP1";
export const RESET_TRAINING_STEP1 = "RESET_TRAINING_STEP1";

//STORE REGISTRATION
export const STORE_REGISTRATION_STEP2 = "STORE_REGISTRATION_STEP2";
export const GET_REGISTRATION_STEP2 = "GET_REGISTRATION_STEP2";
export const RESET_REGISTRATION_STEP2 = "RESET_REGISTRATION_STEP2";

//STORE COMMITMENT
export const STORE_COMMITMENT_STEP3 = "STORE_COMMITMENT_STEP3";
export const GET_COMMITMENT_STEP3 = "GET_COMMITMENT_STEP3";
export const RESET_COMMITMENT_STEP3 = "RESET_COMMITMENT_STEP3";
