//GET_DATA_PRIBADI
export const GET_DATA_PRIBADI_SUCCESS = "GET_DATA_PRIBADI_SUCCESS";
export const GET_DATA_PRIBADI_FAIL = "GET_DATA_PRIBADI_FAIL";

//STORE TRAINING
export const STORE_TRAINING_STEP1 = "STORE_TRAINING_STEP1";
export const GET_TRAINING_STEP1 = "GET_TRAINING_STEP1";
export const RESET_TRAINING_STEP1 = "RESET_TRAINING_STEP1";

//STORE REGISTRATION
export const STORE_REGISTRATION_STEP2 = "STORE_REGISTRATION_STEP2";
export const GET_REGISTRATION_STEP2 = "GET_REGISTRATION_STEP2";
export const RESET_REGISTRATION_STEP2 = "RESET_REGISTRATION_STEP2";

//STORE COMMITMENT
export const STORE_COMMITMENT_STEP3 = "STORE_COMMITMENT_STEP3";
export const GET_COMMITMENT_STEP3 = "GET_COMMITMENT_STEP3";
export const RESET_COMMITMENT_STEP3 = "RESET_COMMITMENT_STEP3";

//DROPDOWN AKADEMI
export const GET_DROPDOWN_AKADEMI = "GET_DROPDOWN_AKADEMI";
export const ERROR_DROPDOWN_AKADEMI = "ERROR_DROPDOWN_AKADEMI";
//DROPDOWN TEMA
export const GET_DROPDOWN_TEMA = "GET_DROPDOWN_TEMA";
export const ERROR_DROPDOWN_TEMA = "ERROR_DROPDOWN_TEMA";
//DROPDOWN PELATIHAN
export const GET_DROPDOWN_PELATIHAN = "GET_DROPDOWN_PELATIHAN";
export const ERROR_DROPDOWN_PELATIHAN = "ERROR_DROPDOWN_PELATIHAN";
//DROPDOWN LEVEL_PELATIHAN
export const GET_DROPDOWN_LEVEL_PELATIHAN = "GET_DROPDOWN_LEVEL_PELATIHAN";
export const ERROR_DROPDOWN_LEVEL_PELATIHAN = "ERROR_DROPDOWN_LEVEL_PELATIHAN";
//DROPDOWN MITRA
export const GET_DROPDOWN_MITRA = "GET_DROPDOWN_MITRA";
export const ERROR_DROPDOWN_MITRA = "ERROR_DROPDOWN_MITRA";
//DROPDOWN ZONASI
export const GET_DROPDOWN_ZONASI = "GET_DROPDOWN_ZONASI";
export const ERROR_DROPDOWN_ZONASI = "ERROR_DROPDOWN_ZONASI";
//DROPDOWN PROVINSI
export const GET_DROPDOWN_PROVINSI = "GET_DROPDOWN_PROVINSI";
export const ERROR_DROPDOWN_PROVINSI = "ERROR_DROPDOWN_PROVINSI";
//DROPDOWN KABUPATEN
export const GET_DROPDOWN_KABUPATEN = "GET_DROPDOWN_KABUPATEN";
export const ERROR_DROPDOWN_KABUPATEN = "ERROR_DROPDOWN_KABUPATEN";
//DROPDOWN PENYELENGGARA
export const GET_DROPDOWN_PENYELENGGARA = "GET_DROPDOWN_PENYELENGGARA";
export const ERROR_DROPDOWN_PENYELENGGARA = "ERROR_DROPDOWN_PENYELENGGARA";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
