//GET_DATA_PRIBADI
export const GET_DATA_PRIBADI_SUCCESS = "GET_DATA_PRIBADI_SUCCESS";
export const GET_DATA_PRIBADI_FAIL = "GET_DATA_PRIBADI_FAIL";

//STORE FORM_REGISTER
export const STORE_FORM_REGISTER = "STORE_FORM_REGISTER";
export const GET_FORM_REGISTER = "GET_FORM_REGISTER";
export const RESET_FORM_REGISTER = "RESET_FORM_REGISTER";

//STORE TRAINING
export const STORE_TRAINING_STEP1 = "STORE_TRAINING_STEP1";
export const GET_TRAINING_STEP1 = "GET_TRAINING_STEP1";
export const RESET_TRAINING_STEP1 = "RESET_TRAINING_STEP1";

//STORE REGISTRATION
export const STORE_REGISTRATION_STEP2 = "STORE_REGISTRATION_STEP2";
export const GET_REGISTRATION_STEP2 = "GET_REGISTRATION_STEP2";
export const RESET_REGISTRATION_STEP2 = "RESET_REGISTRATION_STEP2";

//STORE COMMITMENT
export const STORE_COMMITMENT_STEP3 = "STORE_COMMITMENT_STEP3";
export const GET_COMMITMENT_STEP3 = "GET_COMMITMENT_STEP3";
export const RESET_COMMITMENT_STEP3 = "RESET_COMMITMENT_STEP3";

//DROPDOWN AKADEMI
export const GET_DROPDOWN_AKADEMI = "GET_DROPDOWN_AKADEMI";
export const ERROR_DROPDOWN_AKADEMI = "ERROR_DROPDOWN_AKADEMI";
//DROPDOWN TEMA
export const GET_DROPDOWN_TEMA = "GET_DROPDOWN_TEMA";
export const ERROR_DROPDOWN_TEMA = "ERROR_DROPDOWN_TEMA";
//DROPDOWN TEMA BY AKADEMI
export const GET_DROPDOWN_TEMA_BY_AKADEMI = "GET_DROPDOWN_TEMA_BY_AKADEMI";
export const ERROR_DROPDOWN_TEMA_BY_AKADEMI = "ERROR_DROPDOWN_TEMA_BY_AKADEMI";
//DROPDOWN AGAMA
export const GET_DROPDOWN_AGAMA = "GET_DROPDOWN_AGAMA";
export const ERROR_DROPDOWN_AGAMA = "ERROR_DROPDOWN_AGAMA";
//DROPDOWN STATUS_PEKERJAAN
export const GET_DROPDOWN_STATUS_PEKERJAAN = "GET_DROPDOWN_STATUS_PEKERJAAN";
export const ERROR_DROPDOWN_STATUS_PEKERJAAN =
  "ERROR_DROPDOWN_STATUS_PEKERJAAN";
//DROPDOWN PELATIHAN
export const GET_DROPDOWN_PELATIHAN = "GET_DROPDOWN_PELATIHAN";
export const ERROR_DROPDOWN_PELATIHAN = "ERROR_DROPDOWN_PELATIHAN";
//DROPDOWN PELATIHAN BY TEMA
export const GET_DROPDOWN_PELATIHAN_BY_TEMA = "GET_DROPDOWN_PELATIHAN_BY_TEMA";
export const ERROR_DROPDOWN_PELATIHAN_BY_TEMA =
  "ERROR_DROPDOWN_PELATIHAN_BY_TEMA";
//DROPDOWN PENDIDIKAN
export const GET_DROPDOWN_PENDIDIKAN = "GET_DROPDOWN_PENDIDIKAN";
export const ERROR_DROPDOWN_PENDIDIKAN = "ERROR_DROPDOWN_PENDIDIKAN";
//DROPDOWN LEVEL_PELATIHAN
export const GET_DROPDOWN_LEVEL_PELATIHAN = "GET_DROPDOWN_LEVEL_PELATIHAN";
export const ERROR_DROPDOWN_LEVEL_PELATIHAN = "ERROR_DROPDOWN_LEVEL_PELATIHAN";
//DROPDOWN MITRA
export const GET_DROPDOWN_MITRA = "GET_DROPDOWN_MITRA";
export const ERROR_DROPDOWN_MITRA = "ERROR_DROPDOWN_MITRA";
//DROPDOWN ZONASI
export const GET_DROPDOWN_ZONASI = "GET_DROPDOWN_ZONASI";
export const ERROR_DROPDOWN_ZONASI = "ERROR_DROPDOWN_ZONASI";
//DROPDOWN PROVINSI
export const GET_DROPDOWN_PROVINSI = "GET_DROPDOWN_PROVINSI";
export const ERROR_DROPDOWN_PROVINSI = "ERROR_DROPDOWN_PROVINSI";
//DROPDOWN KABUPATEN
export const GET_DROPDOWN_KABUPATEN = "GET_DROPDOWN_KABUPATEN";
export const ERROR_DROPDOWN_KABUPATEN = "ERROR_DROPDOWN_KABUPATEN";
//DROPDOWN KABUPATEN_DOMISILI
export const GET_DROPDOWN_KABUPATEN_DOMISILI =
  "GET_DROPDOWN_KABUPATEN_DOMISILI";
export const ERROR_DROPDOWN_KABUPATEN_DOMISILI =
  "ERROR_DROPDOWN_KABUPATEN_DOMISILI";
//DROPDOWN PENYELENGGARA
export const GET_DROPDOWN_PENYELENGGARA = "GET_DROPDOWN_PENYELENGGARA";
export const ERROR_DROPDOWN_PENYELENGGARA = "ERROR_DROPDOWN_PENYELENGGARA";

// DROPDOWN PROVINSI TO DESA
export const GET_DROPDOWN_PROVINSI_TO_DESA = "GET_DROPDOWN_PROVINSI_TO_DESA";
export const ERROR_DROPDOWN_PROVINSI_TO_DESA =
  "ERROR_DROPDOWN_PROVINSI_TO_DESA";

// DROPDOWN KECAMATAN TO DESA
export const GET_DROPDOWN_KECAMATAN_TO_DESA = "GET_DROPDOWN_KECAMATAN_TO_DESA";
export const ERROR_DROPDOWN_KECAMATAN_TO_DESA =
  "ERROR_DROPDOWN_KECAMATAN_TO_DESA";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
