export const LIST_MASTER_TRAINING_REQUEST = "LIST_MASTER_TRAINING_REQUEST";
export const LIST_MASTER_TRAINING_SUCCESS = "LIST_MASTER_TRAINING_SUCCESS";
export const LIST_MASTER_TRAINING_FAIL = "LIST_MASTER_TRAINING_FAIL";

export const NEW_MASTER_TRAINING_REQUEST = "NEW_MASTER_TRAINING_REQUEST";
export const NEW_MASTER_TRAINING_SUCCESS = "NEW_MASTER_TRAINING_SUCCESS";
export const NEW_MASTER_TRAINING_FAIL = "NEW_MASTER_TRAINING_FAIL";
export const NEW_MASTER_TRAINING_RESET = "NEW_MASTER_TRAINING_RESET";

export const DETAIL_MASTER_TRAINING_REQUEST = "DETAIL_MASTER_TRAINING_REQUEST";
export const DETAIL_MASTER_TRAINING_SUCCESS = "DETAIL_MASTER_TRAINING_SUCCESS";
export const DETAIL_MASTER_TRAINING_FAIL = "DETAIL_MASTER_TRAINING_FAIL";

export const UPDATE_MASTER_TRAINING_REQUEST = "UPDATE_MASTER_TRAINING_REQUEST";
export const UPDATE_MASTER_TRAINING_SUCCESS = "UPDATE_MASTER_TRAINING_SUCCESS";
export const UPDATE_MASTER_TRAINING_RESET = "UPDATE_MASTER_TRAINING_RESET";
export const UPDATE_MASTER_TRAINING_FAIL = "UPDATE_MASTER_TRAINING_FAIL";

export const DELETE_MASTER_TRAINING_REQUEST = "DELETE_MASTER_TRAINING_REQUEST";
export const DELETE_MASTER_TRAINING_SUCCESS = "DELETE_MASTER_TRAINING_SUCCESS";
export const DELETE_MASTER_TRAINING_RESET = "DELETE_MASTER_TRAINING_RESET";
export const DELETE_MASTER_TRAINING_FAIL = "DELETE_MASTER_TRAINING_FAIL";

export const SET_KEYWORD_VALUE = "SET_KEYWORD_VALUE";
export const SET_PAGE_VALUE = "SET_PAGE_VALUE";
export const SET_LIMIT_VALUE = "SET_LIMIT_VALUE";
export const RESET_VALUE_FILTER = "RESET_VALUE_FILTER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
