export const LIST_TRAINING_REQUEST = "LIST_TRAINING_REQUEST";
export const LIST_TRAINING_SUCCESS = "LIST_TRAINING_SUCCESS";
export const LIST_TRAINING_FAIL = "LIST_TRAINING_FAIL";

export const SET_KEYWORD_VALUE = "SET_KEYWORD_VALUE";
export const SET_PENYELENGGARA_VALUE = "SET_PENYELENGGARA_VALUE";
export const SET_KATEGORI_PESERTA_VALUE = "SET_KATEGORI_PESERTA_VALUE";
export const SET_PELATIHAN_MULAI_VALUE = "SET_PELATIHAN_MULAI_VALUE";
export const SET_PELATIHAN_AKHIR_VALUE = "SET_PELATIHAN_AKHIR_VALUE";

export const SET_PAGE_VALUE = "SET_PAGE_VALUE";
export const SET_LIMIT_VALUE = "SET_LIMIT_VALUE";
export const RESET_STATUS_FILTER = "RESET_STATUS_FILTER";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
