//UPDATE_DATA_PRIBADI
export const UPDATE_DATA_PRIBADI_REQUEST = "UPDATE_DATA_PRIBADI_REQUEST";
export const UPDATE_DATA_PRIBADI_SUCCESS = "UPDATE_DATA_PRIBADI_SUCCESS";
export const UPDATE_DATA_PRIBADI_FAIL = "UPDATE_DATA_PRIBADI_FAIL";
export const UPDATE_DATA_PRIBADI_RESET = "UPDATE_DATA_PRIBADI_RESET";

//GET_ALAMAT
export const GET_ALAMAT_SUCCESS = "GET_ALAMAT_SUCCESS";
export const GET_ALAMAT_FAIL = "GET_ALAMAT_FAIL";

//UPDATE_ALAMAT
export const UPDATE_ALAMAT_REQUEST = "UPDATE_ALAMAT_REQUEST";
export const UPDATE_ALAMAT_SUCCESS = "UPDATE_ALAMAT_SUCCESS";
export const UPDATE_ALAMAT_FAIL = "UPDATE_ALAMAT_FAIL";
export const UPDATE_ALAMAT_RESET = "UPDATE_ALAMAT_RESET";

//GET_PENDIDIKAN
export const GET_PENDIDIKAN_SUCCESS = "GET_PENDIDIKAN_SUCCESS";
export const GET_PENDIDIKAN_FAIL = "GET_PENDIDIKAN_FAIL";
export const GET_ASAL_SEKOLAH = "GET_ASAL_SEKOLAH";

//UPDATE_PENDIDIKAN
export const UPDATE_PENDIDIKAN_REQUEST = "UPDATE_PENDIDIKAN_REQUEST";
export const UPDATE_PENDIDIKAN_SUCCESS = "UPDATE_PENDIDIKAN_SUCCESS";
export const UPDATE_PENDIDIKAN_FAIL = "UPDATE_PENDIDIKAN_FAIL";
export const UPDATE_PENDIDIKAN_RESET = "UPDATE_PENDIDIKAN_RESET";

//GET_KETERAMPILAN
export const GET_KETERAMPILAN_SUCCESS = "GET_KETERAMPILAN_SUCCESS";
export const GET_KETERAMPILAN_FAIL = "GET_KETERAMPILAN_FAIL";

//UPDATE_KETERAMPILAN
export const UPDATE_KETERAMPILAN_REQUEST = "UPDATE_KETERAMPILAN_REQUEST";
export const UPDATE_KETERAMPILAN_SUCCESS = "UPDATE_KETERAMPILAN_SUCCESS";
export const UPDATE_KETERAMPILAN_FAIL = "UPDATE_KETERAMPILAN_FAIL";
export const UPDATE_KETERAMPILAN_RESET = "UPDATE_KETERAMPILAN_RESET";

//GET_PEKERJAAN
export const GET_PEKERJAAN_SUCCESS = "GET_PEKERJAAN_SUCCESS";
export const GET_PEKERJAAN_FAIL = "GET_PEKERJAAN_FAIL";

//UPDATE_PEKERJAAN
export const UPDATE_PEKERJAAN_REQUEST = "UPDATE_PEKERJAAN_REQUEST";
export const UPDATE_PEKERJAAN_SUCCESS = "UPDATE_PEKERJAAN_SUCCESS";
export const UPDATE_PEKERJAAN_FAIL = "UPDATE_PEKERJAAN_FAIL";
export const UPDATE_PEKERJAAN_RESET = "UPDATE_PEKERJAAN_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
