//GET_FORM_BUILDER
export const GET_FORM_BUILDER_SUCCESS = "GET_FORM_BUILDER_SUCCESS";
export const GET_FORM_BUILDER_FAIL = "GET_FORM_BUILDER_FAIL";

//PENDAFTARAN_PELATIHAN
export const PENDAFTARAN_PELATIHAN_REQUEST = "PENDAFTARAN_PELATIHAN_REQUEST";
export const PENDAFTARAN_PELATIHAN_SUCCESS = "PENDAFTARAN_PELATIHAN_SUCCESS";
export const PENDAFTARAN_PELATIHAN_RESET = "PENDAFTARAN_PELATIHAN_RESET";
export const PENDAFTARAN_PELATIHAN_FAIL = "PENDAFTARAN_PELATIHAN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
