//LIST_REVIEW
export const LIST_REVIEW_REQUEST = "LIST_REVIEW_REQUEST";
export const LIST_REVIEW_SUCCESS = "LIST_REVIEW_SUCCESS";
export const LIST_REVIEW_FAIL = "LIST_REVIEW_FAIL";

//REVISI_REVIEW
export const REVISI_REVIEW_REQUEST = "REVISI_REVIEW_REQUEST";
export const REVISI_REVIEW_SUCCESS = "REVISI_REVIEW_SUCCESS";
export const REVISI_REVIEW_FAIL = "REVISI_REVIEW_FAIL";
export const REVISI_REVIEW_RESET = "REVISI_REVIEW_RESET";

//TOLAK_REVIEW
export const TOLAK_REVIEW_REQUEST = "TOLAK_REVIEW_REQUEST";
export const TOLAK_REVIEW_SUCCESS = "TOLAK_REVIEW_SUCCESS";
export const TOLAK_REVIEW_FAIL = "TOLAK_REVIEW_FAIL";
export const TOLAK_REVIEW_RESET = "TOLAK_REVIEW_RESET";

//CARD_REVIEW
export const CARD_REVIEW_SUCCESS = "CARD_REVIEW_SUCCESS";
export const CARD_REVIEW_FAIL = "CARD_REVIEW_FAIL";

//GET_LIST_REVISI
export const GET_LIST_REVISI_SUCCESS = "GET_LIST_REVISI_SUCCESS";
export const GET_LIST_REVISI_FAIL = "GET_LIST_REVISI_FAIL";

// GET REVIEW STEP 1
export const GET_REVIEW_STEP1_SUCCESS = "GET_REVIEW_STEP1_SUCCESS";
export const GET_REVIEW_STEP1_FAIL = "GET_REVIEW_STEP1_FAIL";

// GET REVIEW STEP 2
export const GET_REVIEW_STEP2_SUCCESS = "GET_REVIEW_STEP2_SUCCESS";
export const GET_REVIEW_STEP2_FAIL = "GET_REVIEW_STEP2_FAIL";

// GET REVIEW STEP 3
export const GET_REVIEW_STEP3_SUCCESS = "GET_REVIEW_STEP3_SUCCESS";
export const GET_REVIEW_STEP3_FAIL = "GET_REVIEW_STEP3_FAIL";

export const GET_REVIEW_STEP4_SUCCESS = "GET_REVIEW_STEP4_SUCCESS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
