//Dashboard Peserta
export const RIWAYAT_PELATIHAN_REQUEST = "RIWAYAT_PELATIHAN_REQUEST";
export const RIWAYAT_PELATIHAN_SUCCESS = "RIWAYAT_PELATIHAN_SUCCESS";
export const RIWAYAT_PELATIHAN_FAIL = "RIWAYAT_PELATIHAN_FAIL";

export const SET_KEYWORD_VALUE = "SET_KEYWORD_VALUE";
export const SET_PESERTA_VALUE = "SET_PESERTA_VALUE";
export const SET_PAGE_VALUE = "SET_PAGE_VALUE";
export const SET_LIMIT_VALUE = "SET_LIMIT_VALUE";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const RIWAYAT_PELATIHAN_DETAIL_REQUEST =
  "RIWAYAT_PELATIHAN_DETAIL_REQUEST";
export const RIWAYAT_PELATIHAN_DETAIL_SUCCESS =
  "RIWAYAT_PELATIHAN_DETAIL_SUCCESS";
export const RIWAYAT_PELATIHAN_DETAIL_FAIL = "RIWAYAT_PELATIHAN_DETAIL_FAIL";
