//Dashboard Peserta
export const RIWAYAT_PELATIHAN_REQUEST = "RIWAYAT_PELATIHAN_REQUEST";
export const RIWAYAT_PELATIHAN_SUCCESS = "RIWAYAT_PELATIHAN_SUCCESS";
export const RIWAYAT_PELATIHAN_FAIL = "RIWAYAT_PELATIHAN_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
