//SUMMARY
export const SUMMARY_REQUEST = "SUMMARY_REQUEST";
export const SUMMARY_SUCCESS = "SUMMARY_SUCCESS";
export const SUMMARY_FAIL = "SUMMARY_FAIL";

// AKADEMI BY PELATIHAN
export const GET_AKADEMI_BY_PELATIHAN_SUCCESS =
  "GET_AKADEMI_BY_PELATIHAN_SUCCESS";
export const GET_AKADEMI_BY_PELATIHAN_FAIL = "GET_AKADEMI_BY_PELATIHAN_FAIL";

// REKAP_PENDAFTARAN_PESERTA
export const GET_REKAP_PENDAFTARAN_PESERTA_REQUEST =
  "GET_REKAP_PENDAFTARAN_PESERTA_REQUEST";
export const GET_REKAP_PENDAFTARAN_PESERTA_SUCCESS =
  "GET_REKAP_PENDAFTARAN_PESERTA_SUCCESS";
export const GET_REKAP_PENDAFTARAN_PESERTA_FAIL =
  "GET_REKAP_PENDAFTARAN_PESERTA_FAIL";

// STATUS_PENDAFTAR
export const GET_STATUS_PENDAFTAR_SUCCESS = "GET_STATUS_PENDAFTAR_SUCCESS";
export const GET_STATUS_PENDAFTAR_FAIL = "GET_STATUS_PENDAFTAR_FAIL";

// REMINDER_BERKAS
export const GET_REMINDER_BERKAS_SUCCESS = "GET_REMINDER_BERKAS_SUCCESS";
export const GET_REMINDER_BERKAS_FAIL = "GET_REMINDER_BERKAS_FAIL";

// DATA_PRIBADI
export const GET_DATA_PRIBADI_SUCCESS = "GET_DATA_PRIBADI_SUCCESS";
export const GET_DATA_PRIBADI_FAIL = "GET_DATA_PRIBADI_FAIL";

// RIWAYAT_PELATIHAN
export const GET_RIWAYAT_PELATIHAN_SUCCESS = "GET_RIWAYAT_PELATIHAN_SUCCESS";
export const GET_RIWAYAT_PELATIHAN_FAIL = "GET_RIWAYAT_PELATIHAN_FAIL";

// BERKAS_PENDAFTARAN
export const GET_BERKAS_PENDAFTARAN_SUCCESS = "GET_BERKAS_PENDAFTARAN_SUCCESS";
export const GET_BERKAS_PENDAFTARAN_FAIL = "GET_BERKAS_PENDAFTARAN_FAIL";

// FORM_KOMITMEN
export const GET_FORM_KOMITMEN_SUCCESS = "GET_FORM_KOMITMEN_SUCCESS";
export const GET_FORM_KOMITMEN_FAIL = "GET_FORM_KOMITMEN_FAIL";

// FORM_LPJ
export const GET_FORM_LPJ_SUCCESS = "GET_FORM_LPJ_SUCCESS";
export const GET_FORM_LPJ_FAIL = "GET_FORM_LPJ_FAIL";
export const NEW_LPJ_REQUEST = "NEW_LPJ_REQUEST";
export const NEW_LPJ_SUCCESS = "NEW_LPJ_SUCCESS";
export const NEW_LPJ_FAIL = "NEW_LPJ_FAIL";
export const NEW_LPJ_RESET = "NEW_LPJ_RESET";

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_RESET = "UPDATE_STATUS_RESET";
export const UPDATE_STATUS_FAIL = "UPDATE_STATUS_FAIL";

export const UPDATE_REMINDER_SUCCESS = "UPDATE_REMINDER_SUCCESS";
export const UPDATE_REMINDER_RESET = "UPDATE_REMINDER_RESET";
export const UPDATE_REMINDER_FAIL = "UPDATE_REMINDER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
