export const THEME_REQUEST = "THEME_REQUEST";
export const THEME_SUCCESS = "THEME_SUCCESS";
export const THEME_FAIL = "THEME_FAIL";

export const NEW_THEME_REQUEST = "NEW_THEME_REQUEST";
export const NEW_THEME_SUCCESS = "NEW_THEME_SUCCESS";
export const NEW_THEME_RESET = "NEW_THEME_RESET";
export const NEW_THEME_FAIL = "NEW_THEME_FAIL";

export const DETAIL_THEME_REQUEST = "DETAIL_THEME_REQUEST";
export const DETAIL_THEME_SUCCESS = "DETAIL_THEME_SUCCESS";
export const DETAIL_THEME_FAIL = "DETAIL_THEME_FAIL";

export const UPDATE_THEME_REQUEST = "UPDATE_THEME_REQUEST";
export const UPDATE_THEME_SUCCESS = "UPDATE_THEME_SUCCESS";
export const UPDATE_THEME_RESET = "UPDATE_THEME_RESET";
export const UPDATE_THEME_FAIL = "UPDATE_THEME_FAIL";

export const DELETE_THEME_REQUEST = "DELETE_THEME_REQUEST";
export const DELETE_THEME_SUCCESS = "DELETE_THEME_SUCCESS";
export const DELETE_THEME_RESET = "DELETE_THEME_RESET";
export const DELETE_THEME_FAIL = "DELETE_THEME_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
