//TRAINING
export const TRAINING_REQUEST = "TRAINING_REQUEST";
export const TRAINING_SUCCESS = "TRAINING_SUCCESS";
export const TRAINING_FAIL = "TRAINING_FAIL";

//CARD_TRAINING
export const CARD_TRAINING_SUCCESS = "CARD_TRAINING_SUCCESS";
export const CARD_TRAINING_FAIL = "CARD_TRAINING_FAIL";

//UPDATE STATUS PUBLISH
export const REQUEST_STATUS_PUBLISH = "REQUEST_STATUS_PUBLISH";
export const UPDATE_STATUS_PUBLISH = "UPDATE_STATUS_PUBLISH";
export const FAIL_STATUS_PUBLISH = "FAIL_STATUS_PUBLISH";
export const CLEAR_STATUS = "CLEAR_STATUS";

//UPDATE STATUS PELATIHAN
export const REQUEST_STATUS_PELATIHAN = "REQUEST_STATUS_PELATIHAN";
export const UPDATE_STATUS_PELATIHAN = "UPDATE_STATUS_PELATIHAN";
export const FAIL_STATUS_PELATIHAN = "FAIL_STATUS_PELATIHAN";

//NEW TRAINING
export const NEW_TRAINING_STEP1_REQUEST = "NEW_TRAINING_STEP1_REQUEST";
export const NEW_TRAINING_STEP1_SUCCESS = "NEW_TRAINING_STEP1_SUCCESS";
export const NEW_TRAINING_STEP1_RESET = "NEW_TRAINING_STEP1_RESET";
export const NEW_TRAINING_STEP1_FAIL = "NEW_TRAINING_STEP1_FAIL";

export const NEW_TRAINING_STEP2_REQUEST = "NEW_TRAINING_STEP2_REQUEST";
export const NEW_TRAINING_STEP2_SUCCESS = "NEW_TRAINING_STEP2_SUCCESS";
export const NEW_TRAINING_STEP2_RESET = "NEW_TRAINING_STEP2_RESET";
export const NEW_TRAINING_STEP2_FAIL = "NEW_TRAINING_STEP2_FAIL";

export const NEW_TRAINING_STEP3_REQUEST = "NEW_TRAINING_STEP3_REQUEST";
export const NEW_TRAINING_STEP3_SUCCESS = "NEW_TRAINING_STEP3_SUCCESS";
export const NEW_TRAINING_STEP3_RESET = "NEW_TRAINING_STEP3_RESET";
export const NEW_TRAINING_STEP3_FAIL = "NEW_TRAINING_STEP3_FAIL";
//END NEW TRAINING

//DETAIL TRAINING
export const DETAIL_TRAINING_STEP1_REQUEST = "DETAIL_TRAINING_STEP1_REQUEST";
export const DETAIL_TRAINING_STEP1_SUCCESS = "DETAIL_TRAINING_STEP1_SUCCESS";
export const DETAIL_TRAINING_STEP1_FAIL = "DETAIL_TRAINING_STEP1_FAIL";

export const DETAIL_TRAINING_STEP2_REQUEST = "DETAIL_TRAINING_STEP2_REQUEST";
export const DETAIL_TRAINING_STEP2_SUCCESS = "DETAIL_TRAINING_STEP2_SUCCESS";
export const DETAIL_TRAINING_STEP2_FAIL = "DETAIL_TRAINING_STEP2_FAIL";

export const DETAIL_TRAINING_STEP3_REQUEST = "DETAIL_TRAINING_STEP3_REQUEST";
export const DETAIL_TRAINING_STEP3_SUCCESS = "DETAIL_TRAINING_STEP3_SUCCESS";
export const DETAIL_TRAINING_STEP3_FAIL = "DETAIL_TRAINING_STEP3_FAIL";

export const DETAIL_TRAINING_STEP4_REQUEST = "DETAIL_TRAINING_STEP4_REQUEST";
export const DETAIL_TRAINING_STEP4_SUCCESS = "DETAIL_TRAINING_STEP4_SUCCESS";
export const DETAIL_TRAINING_STEP4_FAIL = "DETAIL_TRAINING_STEP4_FAIL";
//END DETAIL TRAINING

//UPDATE TRAINING
export const UPDATE_TRAINING_STEP1_REQUEST = "UPDATE_TRAINING_STEP1_REQUEST";
export const UPDATE_TRAINING_STEP1_SUCCESS = "UPDATE_TRAINING_STEP1_SUCCESS";
export const UPDATE_TRAINING_STEP1_RESET = "UPDATE_TRAINING_STEP1_RESET";
export const UPDATE_TRAINING_STEP1_FAIL = "UPDATE_TRAINING_STEP1_FAIL";

export const UPDATE_TRAINING_STEP2_REQUEST = "UPDATE_TRAINING_STEP2_REQUEST";
export const UPDATE_TRAINING_STEP2_SUCCESS = "UPDATE_TRAINING_STEP2_SUCCESS";
export const UPDATE_TRAINING_STEP2_RESET = "UPDATE_TRAINING_STEP2_RESET";
export const UPDATE_TRAINING_STEP2_FAIL = "UPDATE_TRAINING_STEP2_FAIL";

export const UPDATE_TRAINING_STEP3_REQUEST = "UPDATE_TRAINING_STEP3_REQUEST";
export const UPDATE_TRAINING_STEP3_SUCCESS = "UPDATE_TRAINING_STEP3_SUCCESS";
export const UPDATE_TRAINING_STEP3_RESET = "UPDATE_TRAINING_STEP3_RESET";
export const UPDATE_TRAINING_STEP3_FAIL = "UPDATE_TRAINING_STEP3_FAIL";
//END UPDATE TRAINING

export const DELETE_TRAINING_REQUEST = "DELETE_TRAINING_REQUEST";
export const DELETE_TRAINING_SUCCESS = "DELETE_TRAINING_SUCCESS";
export const DELETE_TRAINING_RESET = "DELETE_TRAINING_RESET";
export const DELETE_TRAINING_FAIL = "DELETE_TRAINING_FAIL";
//END TRAINING

//DETAIL LPJ
export const DETAIL_LPJ_REQUEST = "DETAIL_LPJ_REQUEST";
export const DETAIL_LPJ_SUCCESS = "DETAIL_LPJ_SUCCESS";
export const DETAIL_LPJ_FAIL = "DETAIL_LPJ_FAIL";

//ADD LPJ
export const ADD_LPJ_REQUEST = "ADD_LPJ_REQUEST";
export const ADD_LPJ_SUCCESS = "ADD_LPJ_SUCCESS";
export const ADD_LPJ_RESET = "ADD_LPJ_RESET";
export const ADD_LPJ_FAIL = "ADD_LPJ_FAIL";

//DETAIL EVIDENCE
export const DETAIL_EVIDENCE_REQUEST = "DETAIL_EVIDENCE_REQUEST";
export const DETAIL_EVIDENCE_SUCCESS = "DETAIL_EVIDENCE_SUCCESS";
export const DETAIL_EVIDENCE_FAIL = "DETAIL_EVIDENCE_FAIL";

//ADD EVIDENCE
export const ADD_EVIDENCE_REQUEST = "ADD_EVIDENCE_REQUEST";
export const ADD_EVIDENCE_SUCCESS = "ADD_EVIDENCE_SUCCESS";
export const ADD_EVIDENCE_RESET = "ADD_EVIDENCE_RESET";
export const ADD_EVIDENCE_FAIL = "ADD_EVIDENCE_FAIL";

//CLONE EVIDENCE
export const CLONE_TRAINING_REQUEST = "CLONE_TRAINING_REQUEST";
export const CLONE_TRAINING_SUCCESS = "CLONE_TRAINING_SUCCESS";
export const CLONE_TRAINING_RESET = "CLONE_TRAINING_RESET";
export const CLONE_TRAINING_FAIL = "CLONE_TRAINING_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_EDIT_DATA_TRAINING = "GET_EDIT_DATA_TRAINING";
export const GET_EDIT_DATA_TRAINING2 = "GET_EDIT_DATA_TRAINING2";
export const GET_EDIT_DATA_TRAINING3 = "GET_EDIT_DATA_TRAINING3";
