export const SUBTANCE_QUESTION_DETAIL_REQUEST =
  "SUBTANCE_QUESTION_DETAIL_REQUEST";
export const SUBTANCE_QUESTION_DETAIL_SUCCESS =
  "SUBTANCE_QUESTION_DETAIL_SUCCESS";
export const SUBTANCE_QUESTION_DETAIL_FAIL = "SUBTANCE_QUESTION_DETAIL_FAIL";

export const SUBTANCE_QUESTION_RANDOM_DETAIL_REQUEST =
  "SUBTANCE_QUESTION_RANDOM_DETAIL_REQUEST";
export const SUBTANCE_QUESTION_RANDOM_DETAIL_SUCCESS =
  "SUBTANCE_QUESTION_RANDOM_DETAIL_SUCCESS";
export const SUBTANCE_QUESTION_RANDOM_DETAIL_FAIL =
  "SUBTANCE_QUESTION_RANDOM_DETAIL_FAIL";

export const DASHBOARD_SUBVIT_REQUEST = "DASHBOARD_SUBVIT_REQUEST";
export const DASHBOARD_SUBVIT_SUCCESS = "DASHBOARD_SUBVIT_SUCCESS";
export const DASHBOARD_SUBVIT_FAIL = "DASHBOARD_SUBVIT_FAIL";

export const NEW_SUBTANCE_QUESTION_DETAIL_REQUEST =
  "NEW_SUBTANCE_QUESTION_DETAIL_REQUEST";
export const NEW_SUBTANCE_QUESTION_DETAIL_SUCCESS =
  "NEW_SUBTANCE_QUESTION_DETAIL_SUCCESS";
export const NEW_SUBTANCE_QUESTION_DETAIL_RESET =
  "NEW_SUBTANCE_QUESTION_DETAIL_RESET";
export const NEW_SUBTANCE_QUESTION_DETAIL_FAIL =
  "NEW_SUBTANCE_QUESTION_DETAIL_FAIL";

export const POST_RESULT_REQUEST = "POST_RESULT_REQUEST";
export const POST_RESULT_SUCCESS = "POST_RESULT_SUCCESS";
export const POST_RESULT_RESET = "POST_RESULT_RESET";
export const POST_RESULT_FAIL = "POST_RESULT_FAIL";

export const DETAIL_SUBTANCE_QUESTION_DETAIL_REQUEST =
  "DETAIL_SUBTANCE_QUESTION_DETAIL_REQUEST";
export const DETAIL_SUBTANCE_QUESTION_DETAIL_SUCCESS =
  "DETAIL_SUBTANCE_QUESTION_DETAIL_SUCCESS";
export const DETAIL_SUBTANCE_QUESTION_DETAIL_FAIL =
  "DETAIL_SUBTANCE_QUESTION_DETAIL_FAIL";

export const UPDATE_SUBTANCE_QUESTION_DETAIL_REQUEST =
  "UPDATE_SUBTANCE_QUESTION_DETAIL_REQUEST";
export const UPDATE_SUBTANCE_QUESTION_DETAIL_SUCCESS =
  "UPDATE_SUBTANCE_QUESTION_DETAIL_SUCCESS";
export const UPDATE_SUBTANCE_QUESTION_DETAIL_RESET =
  "UPDATE_SUBTANCE_QUESTION_DETAIL_RESET";
export const UPDATE_SUBTANCE_QUESTION_DETAIL_FAIL =
  "UPDATE_SUBTANCE_QUESTION_DETAIL_FAIL";

export const DELETE_SUBTANCE_QUESTION_DETAIL_REQUEST =
  "DELETE_SUBTANCE_QUESTION_DETAIL_REQUEST";
export const DELETE_SUBTANCE_QUESTION_DETAIL_SUCCESS =
  "DELETE_SUBTANCE_QUESTION_DETAIL_SUCCESS";
export const DELETE_SUBTANCE_QUESTION_DETAIL_RESET =
  "DELETE_SUBTANCE_QUESTION_DETAIL_RESET";
export const DELETE_SUBTANCE_QUESTION_DETAIL_FAIL =
  "DELETE_SUBTANCE_QUESTION_DETAIL_FAIL";

// ==============================================================================================

export const IMPORT_FILE_SUBTANCE_QUESTION_DETAIL_REQUEST =
  "IMPORT_FILE_SUBTANCE_QUESTION_DETAIL_REQUEST";
export const IMPORT_FILE_SUBTANCE_QUESTION_DETAIL_SUCCESS =
  "IMPORT_FILE_SUBTANCE_QUESTION_DETAIL_SUCCESS";
export const IMPORT_FILE_SUBTANCE_QUESTION_DETAIL_RESET =
  "IMPORT_FILE_SUBTANCE_QUESTION_DETAIL_RESET";
export const IMPORT_FILE_SUBTANCE_QUESTION_DETAIL_FAIL =
  "IMPORT_FILE_SUBTANCE_QUESTION_DETAIL_FAIL";

export const IMPORT_IMAGES_SUBTANCE_QUESTION_DETAIL_REQUEST =
  "IMPORT_IMAGES_SUBTANCE_QUESTION_DETAIL_REQUEST";
export const IMPORT_IMAGES_SUBTANCE_QUESTION_DETAIL_SUCCESS =
  "IMPORT_IMAGES_SUBTANCE_QUESTION_DETAIL_SUCCESS";
export const IMPORT_IMAGES_SUBTANCE_QUESTION_DETAIL_RESET =
  "IMPORT_IMAGES_SUBTANCE_QUESTION_DETAIL_RESET";
export const IMPORT_IMAGES_SUBTANCE_QUESTION_DETAIL_FAIL =
  "IMPORT_IMAGES_SUBTANCE_QUESTION_DETAIL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
