export const SUBTANCE_QUESTION_BANKS_REQUEST = 'SUBTANCE_QUESTION_BANKS_REQUEST'
export const SUBTANCE_QUESTION_BANKS_SUCCESS = 'SUBTANCE_QUESTION_BANKS_SUCCESS'
export const SUBTANCE_QUESTION_BANKS_FAIL = 'SUBTANCE_QUESTION_BANKS_FAIL'

export const NEW_SUBTANCE_QUESTION_BANKS_REQUEST = 'NEW_SUBTANCE_QUESTION_BANKS_REQUEST'
export const NEW_SUBTANCE_QUESTION_BANKS_SUCCESS = 'NEW_SUBTANCE_QUESTION_BANKS_SUCCESS'
export const NEW_SUBTANCE_QUESTION_BANKS_RESET = 'NEW_SUBTANCE_QUESTION_BANKS_RESET'
export const NEW_SUBTANCE_QUESTION_BANKS_FAIL = 'NEW_SUBTANCE_QUESTION_BANKS_FAIL'

export const DETAIL_SUBTANCE_QUESTION_BANKS_REQUEST = 'DETAIL_SUBTANCE_QUESTION_BANKS_REQUEST'
export const DETAIL_SUBTANCE_QUESTION_BANKS_SUCCESS = 'DETAIL_SUBTANCE_QUESTION_BANKS_SUCCESS'
export const DETAIL_SUBTANCE_QUESTION_BANKS_FAIL = 'DETAIL_SUBTANCE_QUESTION_BANKS_FAIL'

export const UPDATE_SUBTANCE_QUESTION_BANKS_REQUEST = 'UPDATE_SUBTANCE_QUESTION_BANKS_REQUEST'
export const UPDATE_SUBTANCE_QUESTION_BANKS_SUCCESS = 'UPDATE_SUBTANCE_QUESTION_BANKS_SUCCESS'
export const UPDATE_SUBTANCE_QUESTION_BANKS_RESET = 'UPDATE_SUBTANCE_QUESTION_BANKS_RESET'
export const UPDATE_SUBTANCE_QUESTION_BANKS_FAIL = 'UPDATE_SUBTANCE_QUESTION_BANKS_FAIL'

export const DELETE_SUBTANCE_QUESTION_BANKS_REQUEST = 'DELETE_SUBTANCE_QUESTION_BANKS_REQUEST'
export const DELETE_SUBTANCE_QUESTION_BANKS_SUCCESS = 'DELETE_SUBTANCE_QUESTION_BANKS_SUCCESS'
export const DELETE_SUBTANCE_QUESTION_BANKS_RESET = 'DELETE_SUBTANCE_QUESTION_BANKS_RESET'
export const DELETE_SUBTANCE_QUESTION_BANKS_FAIL = 'DELETE_SUBTANCE_QUESTION_BANKS_FAIL'

// ==============================================================================================
export const UPDATE_SUBTANCE_QUESTION_BANKS_PUBLISH_REQUEST = 'UPDATE_SUBTANCE_QUESTION_BANKS_PUBLISH_REQUEST'
export const UPDATE_SUBTANCE_QUESTION_BANKS_PUBLISH_SUCCESS = 'UPDATE_SUBTANCE_QUESTION_BANKS_PUBLISH_SUCCESS'
export const UPDATE_SUBTANCE_QUESTION_BANKS_PUBLISH_RESET = 'UPDATE_SUBTANCE_QUESTION_BANKS_PUBLISH_RESET'
export const UPDATE_SUBTANCE_QUESTION_BANKS_PUBLISH_FAIL = 'UPDATE_SUBTANCE_QUESTION_BANKS_PUBLISH_FAIL'

export const REPORT_SUBTANCE_QUESTION_BANKS_REQUEST = 'REPORT_SUBTANCE_QUESTION_BANKS_REQUEST'
export const REPORT_SUBTANCE_QUESTION_BANKS_SUCCESS = 'REPORT_SUBTANCE_QUESTION_BANKS_SUCCESS'
export const REPORT_SUBTANCE_QUESTION_BANKS_FAIL = 'REPORT_SUBTANCE_QUESTION_BANKS_FAIL'

export const NEW_CLONE_SUBTANCE_QUESTION_BANKS_REQUEST = 'NEW_CLONE_SUBTANCE_QUESTION_BANKS_REQUEST'
export const NEW_CLONE_SUBTANCE_QUESTION_BANKS_SUCCESS = 'NEW_CLONE_SUBTANCE_QUESTION_BANKS_SUCCESS'
export const NEW_CLONE_SUBTANCE_QUESTION_BANKS_RESET = 'NEW_CLONE_SUBTANCE_QUESTION_BANKS_RESET'
export const NEW_CLONE_SUBTANCE_QUESTION_BANKS_FAIL = 'NEW_CLONE_SUBTANCE_QUESTION_BANKS_FAIL'

export const DELETE_CLONE_SUBTANCE_QUESTION_BANKS_REQUEST = 'DELETE_CLONE_SUBTANCE_QUESTION_BANKS_REQUEST'
export const DELETE_CLONE_SUBTANCE_QUESTION_BANKS_SUCCESS = 'DELETE_CLONE_SUBTANCE_QUESTION_BANKS_SUCCESS'
export const DELETE_CLONE_SUBTANCE_QUESTION_BANKS_RESET = 'DELETE_CLONE_SUBTANCE_QUESTION_BANKS_RESET'
export const DELETE_CLONE_SUBTANCE_QUESTION_BANKS_FAIL = 'DELETE_CLONE_SUBTANCE_QUESTION_BANKS_FAIL'

export const DETAIL_ONE_SUBTANCE_QUESTION_BANKS_REQUEST = 'DETAIL_ONE_SUBTANCE_QUESTION_BANKS_REQUEST'
export const DETAIL_ONE_SUBTANCE_QUESTION_BANKS_SUCCESS = 'DETAIL_ONE_SUBTANCE_QUESTION_BANKS_SUCCESS'
export const DETAIL_ONE_SUBTANCE_QUESTION_BANKS_FAIL = 'DETAIL_ONE_SUBTANCE_QUESTION_BANKS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'