export const SURVEY_QUESTION_DETAIL_REQUEST = 'SURVEY_QUESTION_DETAIL_REQUEST'
export const SURVEY_QUESTION_DETAIL_SUCCESS = 'SURVEY_QUESTION_DETAIL_SUCCESS'
export const SURVEY_QUESTION_DETAIL_FAIL = 'SURVEY_QUESTION_DETAIL_FAIL'

export const NEW_SURVEY_QUESTION_DETAIL_REQUEST = 'NEW_SURVEY_QUESTION_DETAIL_REQUEST'
export const NEW_SURVEY_QUESTION_DETAIL_SUCCESS = 'NEW_SURVEY_QUESTION_DETAIL_SUCCESS'
export const NEW_SURVEY_QUESTION_DETAIL_RESET = 'NEW_SURVEY_QUESTION_DETAIL_RESET'
export const NEW_SURVEY_QUESTION_DETAIL_FAIL = 'NEW_SURVEY_QUESTION_DETAIL_FAIL'

export const DETAIL_SURVEY_QUESTION_DETAIL_REQUEST = 'DETAIL_SURVEY_QUESTION_DETAIL_REQUEST'
export const DETAIL_SURVEY_QUESTION_DETAIL_SUCCESS = 'DETAIL_SURVEY_QUESTION_DETAIL_SUCCESS'
export const DETAIL_SURVEY_QUESTION_DETAIL_FAIL = 'DETAIL_SURVEY_QUESTION_DETAIL_FAIL'

export const UPDATE_SURVEY_QUESTION_DETAIL_REQUEST = 'UPDATE_SURVEY_QUESTION_DETAIL_REQUEST'
export const UPDATE_SURVEY_QUESTION_DETAIL_SUCCESS = 'UPDATE_SURVEY_QUESTION_DETAIL_SUCCESS'
export const UPDATE_SURVEY_QUESTION_DETAIL_RESET = 'UPDATE_SURVEY_QUESTION_DETAIL_RESET'
export const UPDATE_SURVEY_QUESTION_DETAIL_FAIL = 'UPDATE_SURVEY_QUESTION_DETAIL_FAIL'

export const DELETE_SURVEY_QUESTION_DETAIL_REQUEST = 'DELETE_SURVEY_QUESTION_DETAIL_REQUEST'
export const DELETE_SURVEY_QUESTION_DETAIL_SUCCESS = 'DELETE_SURVEY_QUESTION_DETAIL_SUCCESS'
export const DELETE_SURVEY_QUESTION_DETAIL_RESET = 'DELETE_SURVEY_QUESTION_DETAIL_RESET'
export const DELETE_SURVEY_QUESTION_DETAIL_FAIL = 'DELETE_SURVEY_QUESTION_DETAIL_FAIL'

// ==============================================================================================

export const IMPORT_FILE_SURVEY_QUESTION_DETAIL_REQUEST = 'IMPORT_FILE_SURVEY_QUESTION_DETAIL_REQUEST'
export const IMPORT_FILE_SURVEY_QUESTION_DETAIL_SUCCESS = 'IMPORT_FILE_SURVEY_QUESTION_DETAIL_SUCCESS'
export const IMPORT_FILE_SURVEY_QUESTION_DETAIL_RESET = 'IMPORT_FILE_SURVEY_QUESTION_DETAIL_RESET'
export const IMPORT_FILE_SURVEY_QUESTION_DETAIL_FAIL = 'IMPORT_FILE_SURVEY_QUESTION_DETAIL_FAIL'

export const IMPORT_IMAGES_SURVEY_QUESTION_DETAIL_REQUEST = 'IMPORT_IMAGES_SURVEY_QUESTION_DETAIL_REQUEST'
export const IMPORT_IMAGES_SURVEY_QUESTION_DETAIL_SUCCESS = 'IMPORT_IMAGES_SURVEY_QUESTION_DETAIL_SUCCESS'
export const IMPORT_IMAGES_SURVEY_QUESTION_DETAIL_RESET = 'IMPORT_IMAGES_SURVEY_QUESTION_DETAIL_RESET'
export const IMPORT_IMAGES_SURVEY_QUESTION_DETAIL_FAIL = 'IMPORT_IMAGES_SURVEY_QUESTION_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'