export const SURVEY_QUESTION_BANKS_REQUEST = 'SURVEY_QUESTION_BANKS_REQUEST'
export const SURVEY_QUESTION_BANKS_SUCCESS = 'SURVEY_QUESTION_BANKS_SUCCESS'
export const SURVEY_QUESTION_BANKS_FAIL = 'SURVEY_QUESTION_BANKS_FAIL'

export const NEW_SURVEY_QUESTION_BANKS_REQUEST = 'NEW_SURVEY_QUESTION_BANKS_REQUEST'
export const NEW_SURVEY_QUESTION_BANKS_SUCCESS = 'NEW_SURVEY_QUESTION_BANKS_SUCCESS'
export const NEW_SURVEY_QUESTION_BANKS_RESET = 'NEW_SURVEY_QUESTION_BANKS_RESET'
export const NEW_SURVEY_QUESTION_BANKS_FAIL = 'NEW_SURVEY_QUESTION_BANKS_FAIL'

export const DETAIL_SURVEY_QUESTION_BANKS_REQUEST = 'DETAIL_SURVEY_QUESTION_BANKS_REQUEST'
export const DETAIL_SURVEY_QUESTION_BANKS_SUCCESS = 'DETAIL_SURVEY_QUESTION_BANKS_SUCCESS'
export const DETAIL_SURVEY_QUESTION_BANKS_FAIL = 'DETAIL_SURVEY_QUESTION_BANKS_FAIL'

export const UPDATE_SURVEY_QUESTION_BANKS_REQUEST = 'UPDATE_SURVEY_QUESTION_BANKS_REQUEST'
export const UPDATE_SURVEY_QUESTION_BANKS_SUCCESS = 'UPDATE_SURVEY_QUESTION_BANKS_SUCCESS'
export const UPDATE_SURVEY_QUESTION_BANKS_RESET = 'UPDATE_SURVEY_QUESTION_BANKS_RESET'
export const UPDATE_SURVEY_QUESTION_BANKS_FAIL = 'UPDATE_SURVEY_QUESTION_BANKS_FAIL'

export const DELETE_SURVEY_QUESTION_BANKS_REQUEST = 'DELETE_SURVEY_QUESTION_BANKS_REQUEST'
export const DELETE_SURVEY_QUESTION_BANKS_SUCCESS = 'DELETE_SURVEY_QUESTION_BANKS_SUCCESS'
export const DELETE_SURVEY_QUESTION_BANKS_RESET = 'DELETE_SURVEY_QUESTION_BANKS_RESET'
export const DELETE_SURVEY_QUESTION_BANKS_FAIL = 'DELETE_SURVEY_QUESTION_BANKS_FAIL'

// ==============================================================================================
export const UPDATE_SURVEY_QUESTION_BANKS_PUBLISH_REQUEST = 'UPDATE_SURVEY_QUESTION_BANKS_PUBLISH_REQUEST'
export const UPDATE_SURVEY_QUESTION_BANKS_PUBLISH_SUCCESS = 'UPDATE_SURVEY_QUESTION_BANKS_PUBLISH_SUCCESS'
export const UPDATE_SURVEY_QUESTION_BANKS_PUBLISH_RESET = 'UPDATE_SURVEY_QUESTION_BANKS_PUBLISH_RESET'
export const UPDATE_SURVEY_QUESTION_BANKS_PUBLISH_FAIL = 'UPDATE_SURVEY_QUESTION_BANKS_PUBLISH_FAIL'

export const REPORT_SURVEY_QUESTION_BANKS_REQUEST = 'REPORT_SURVEY_QUESTION_BANKS_REQUEST'
export const REPORT_SURVEY_QUESTION_BANKS_SUCCESS = 'REPORT_SURVEY_QUESTION_BANKS_SUCCESS'
export const REPORT_SURVEY_QUESTION_BANKS_FAIL = 'REPORT_SURVEY_QUESTION_BANKS_FAIL'

export const DETAIL_ONE_SURVEY_QUESTION_BANKS_REQUEST = 'DETAIL_ONE_SURVEY_QUESTION_BANKS_REQUEST'
export const DETAIL_ONE_SURVEY_QUESTION_BANKS_SUCCESS = 'DETAIL_ONE_SURVEY_QUESTION_BANKS_SUCCESS'
export const DETAIL_ONE_SURVEY_QUESTION_BANKS_FAIL = 'DETAIL_ONE_SURVEY_QUESTION_BANKS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'