export const TRIVIA_QUESTION_BANKS_REQUEST = 'TRIVIA_QUESTION_BANKS_REQUEST'
export const TRIVIA_QUESTION_BANKS_SUCCESS = 'TRIVIA_QUESTION_BANKS_SUCCESS'
export const TRIVIA_QUESTION_BANKS_FAIL = 'TRIVIA_QUESTION_BANKS_FAIL'

export const NEW_TRIVIA_QUESTION_BANKS_REQUEST = 'NEW_TRIVIA_QUESTION_BANKS_REQUEST'
export const NEW_TRIVIA_QUESTION_BANKS_SUCCESS = 'NEW_TRIVIA_QUESTION_BANKS_SUCCESS'
export const NEW_TRIVIA_QUESTION_BANKS_RESET = 'NEW_TRIVIA_QUESTION_BANKS_RESET'
export const NEW_TRIVIA_QUESTION_BANKS_FAIL = 'NEW_TRIVIA_QUESTION_BANKS_FAIL'

export const DETAIL_TRIVIA_QUESTION_BANKS_REQUEST = 'DETAIL_TRIVIA_QUESTION_BANKS_REQUEST'
export const DETAIL_TRIVIA_QUESTION_BANKS_SUCCESS = 'DETAIL_TRIVIA_QUESTION_BANKS_SUCCESS'
export const DETAIL_TRIVIA_QUESTION_BANKS_FAIL = 'DETAIL_TRIVIA_QUESTION_BANKS_FAIL'

export const UPDATE_TRIVIA_QUESTION_BANKS_REQUEST = 'UPDATE_TRIVIA_QUESTION_BANKS_REQUEST'
export const UPDATE_TRIVIA_QUESTION_BANKS_SUCCESS = 'UPDATE_TRIVIA_QUESTION_BANKS_SUCCESS'
export const UPDATE_TRIVIA_QUESTION_BANKS_RESET = 'UPDATE_TRIVIA_QUESTION_BANKS_RESET'
export const UPDATE_TRIVIA_QUESTION_BANKS_FAIL = 'UPDATE_TRIVIA_QUESTION_BANKS_FAIL'

export const DELETE_TRIVIA_QUESTION_BANKS_REQUEST = 'DELETE_TRIVIA_QUESTION_BANKS_REQUEST'
export const DELETE_TRIVIA_QUESTION_BANKS_SUCCESS = 'DELETE_TRIVIA_QUESTION_BANKS_SUCCESS'
export const DELETE_TRIVIA_QUESTION_BANKS_RESET = 'DELETE_TRIVIA_QUESTION_BANKS_RESET'
export const DELETE_TRIVIA_QUESTION_BANKS_FAIL = 'DELETE_TRIVIA_QUESTION_BANKS_FAIL'

// ==============================================================================================
export const UPDATE_TRIVIA_QUESTION_BANKS_PUBLISH_REQUEST = 'UPDATE_TRIVIA_QUESTION_BANKS_PUBLISH_REQUEST'
export const UPDATE_TRIVIA_QUESTION_BANKS_PUBLISH_SUCCESS = 'UPDATE_TRIVIA_QUESTION_BANKS_PUBLISH_SUCCESS'
export const UPDATE_TRIVIA_QUESTION_BANKS_PUBLISH_RESET = 'UPDATE_TRIVIA_QUESTION_BANKS_PUBLISH_RESET'
export const UPDATE_TRIVIA_QUESTION_BANKS_PUBLISH_FAIL = 'UPDATE_TRIVIA_QUESTION_BANKS_PUBLISH_FAIL'

export const REPORT_TRIVIA_QUESTION_BANKS_REQUEST = 'REPORT_TRIVIA_QUESTION_BANKS_REQUEST'
export const REPORT_TRIVIA_QUESTION_BANKS_SUCCESS = 'REPORT_TRIVIA_QUESTION_BANKS_SUCCESS'
export const REPORT_TRIVIA_QUESTION_BANKS_FAIL = 'REPORT_TRIVIA_QUESTION_BANKS_FAIL'

export const DETAIL_ONE_TRIVIA_QUESTION_BANKS_REQUEST = 'DETAIL_ONE_TRIVIA_QUESTION_BANKS_REQUEST'
export const DETAIL_ONE_TRIVIA_QUESTION_BANKS_SUCCESS = 'DETAIL_ONE_TRIVIA_QUESTION_BANKS_SUCCESS'
export const DETAIL_ONE_TRIVIA_QUESTION_BANKS_FAIL = 'DETAIL_ONE_TRIVIA_QUESTION_BANKS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'