export const TRIVIA_QUESTION_DETAIL_REQUEST = 'TRIVIA_QUESTION_DETAIL_REQUEST'
export const TRIVIA_QUESTION_DETAIL_SUCCESS = 'TRIVIA_QUESTION_DETAIL_SUCCESS'
export const TRIVIA_QUESTION_DETAIL_FAIL = 'TRIVIA_QUESTION_DETAIL_FAIL'

export const NEW_TRIVIA_QUESTION_DETAIL_REQUEST = 'NEW_TRIVIA_QUESTION_DETAIL_REQUEST'
export const NEW_TRIVIA_QUESTION_DETAIL_SUCCESS = 'NEW_TRIVIA_QUESTION_DETAIL_SUCCESS'
export const NEW_TRIVIA_QUESTION_DETAIL_RESET = 'NEW_TRIVIA_QUESTION_DETAIL_RESET'
export const NEW_TRIVIA_QUESTION_DETAIL_FAIL = 'NEW_TRIVIA_QUESTION_DETAIL_FAIL'

export const DETAIL_TRIVIA_QUESTION_DETAIL_REQUEST = 'DETAIL_TRIVIA_QUESTION_DETAIL_REQUEST'
export const DETAIL_TRIVIA_QUESTION_DETAIL_SUCCESS = 'DETAIL_TRIVIA_QUESTION_DETAIL_SUCCESS'
export const DETAIL_TRIVIA_QUESTION_DETAIL_FAIL = 'DETAIL_TRIVIA_QUESTION_DETAIL_FAIL'

export const UPDATE_TRIVIA_QUESTION_DETAIL_REQUEST = 'UPDATE_TRIVIA_QUESTION_DETAIL_REQUEST'
export const UPDATE_TRIVIA_QUESTION_DETAIL_SUCCESS = 'UPDATE_TRIVIA_QUESTION_DETAIL_SUCCESS'
export const UPDATE_TRIVIA_QUESTION_DETAIL_RESET = 'UPDATE_TRIVIA_QUESTION_DETAIL_RESET'
export const UPDATE_TRIVIA_QUESTION_DETAIL_FAIL = 'UPDATE_TRIVIA_QUESTION_DETAIL_FAIL'

export const DELETE_TRIVIA_QUESTION_DETAIL_REQUEST = 'DELETE_TRIVIA_QUESTION_DETAIL_REQUEST'
export const DELETE_TRIVIA_QUESTION_DETAIL_SUCCESS = 'DELETE_TRIVIA_QUESTION_DETAIL_SUCCESS'
export const DELETE_TRIVIA_QUESTION_DETAIL_RESET = 'DELETE_TRIVIA_QUESTION_DETAIL_RESET'
export const DELETE_TRIVIA_QUESTION_DETAIL_FAIL = 'DELETE_TRIVIA_QUESTION_DETAIL_FAIL'

// ==============================================================================================

export const IMPORT_FILE_TRIVIA_QUESTION_DETAIL_REQUEST = 'IMPORT_FILE_TRIVIA_QUESTION_DETAIL_REQUEST'
export const IMPORT_FILE_TRIVIA_QUESTION_DETAIL_SUCCESS = 'IMPORT_FILE_TRIVIA_QUESTION_DETAIL_SUCCESS'
export const IMPORT_FILE_TRIVIA_QUESTION_DETAIL_RESET = 'IMPORT_FILE_TRIVIA_QUESTION_DETAIL_RESET'
export const IMPORT_FILE_TRIVIA_QUESTION_DETAIL_FAIL = 'IMPORT_FILE_TRIVIA_QUESTION_DETAIL_FAIL'

export const IMPORT_IMAGES_TRIVIA_QUESTION_DETAIL_REQUEST = 'IMPORT_IMAGES_TRIVIA_QUESTION_DETAIL_REQUEST'
export const IMPORT_IMAGES_TRIVIA_QUESTION_DETAIL_SUCCESS = 'IMPORT_IMAGES_TRIVIA_QUESTION_DETAIL_SUCCESS'
export const IMPORT_IMAGES_TRIVIA_QUESTION_DETAIL_RESET = 'IMPORT_IMAGES_TRIVIA_QUESTION_DETAIL_RESET'
export const IMPORT_IMAGES_TRIVIA_QUESTION_DETAIL_FAIL = 'IMPORT_IMAGES_TRIVIA_QUESTION_DETAIL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'