export const OPTION_REFERENCE_REQUEST = "OPTION_REFERENCE_REQUEST";
export const OPTION_REFERENCE_SUCCESS = "OPTION_REFERENCE_SUCCESS";
export const OPTION_REFERENCE_FAIL = "OPTION_REFERENCE_FAIL";

export const GET_PENDIDIKAN_REFERENCE_SUCCESS = "GET_PENDIDIKAN_REFERENCE_SUCCESS";
export const GET_PENDIDIKAN_REFERENCE_FAIL = "GET_PENDIDIKAN_REFERENCE_FAIL";