export const API_REQUEST = "API_REQUEST";
export const API_SUCCESS = "API_SUCCESS";
export const API_FAIL = "API_FAIL";

export const GET_LIST_API_REQUEST = "GET_LIST_API_REQUEST";
export const GET_LIST_API_SUCCESS = "GET_LIST_API_SUCCESS";
export const GET_LIST_API_FAIL = "GET_LIST_API_FAIL";

export const GET_LIST_FIELD_REQUEST = "GET_LIST_FIELD_REQUEST";
export const GET_LIST_FIELD_SUCCESS = "GET_LIST_FIELD_SUCCESS";
export const GET_LIST_FIELD_FAIL = "GET_LIST_FIELD_FAIL";

export const DETAIL_API_REQUEST = "DETAIL_API_REQUEST";
export const DETAIL_API_SUCCESS = "DETAIL_API_SUCCESS";
export const DETAIL_API_FAIL = "DETAIL_API_FAIL";
export const DETAIL_API_RESET = "DETAIL_API_RESET";

export const DELETE_API_SUCCESS = "DELETE_API_SUCCESS";
export const DELETE_API_FAIL = "DELETE_API_FAIL";
export const DELETE_API_RESET = "DELETE_API_RESET";
export const DELETE_API_REQUEST = "DELETE_API_REQUEST";

export const POST_API_REQUEST = "POST_API_REQUEST";
export const POST_API_SUCCESS = "POST_API_SUCCESS";
export const POST_API_FAIL = "POST_API_FAIL";
export const POST_API_RESET = "POST_API_RESET";

export const UPDATE_API_REQUEST = "UPDATE_API_REQUEST";
export const UPDATE_API_SUCCESS = "UPDATE_API_SUCCESS";
export const UPDATE_API_FAIL = "UPDATE_API_FAIL";
export const UPDATE_API_RESET = "UPDATE_API_RESET";

export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
