export const GENERAL_REQUEST = "GENERAL_REQUEST";
export const GENERAL_SUCCESS = "GENERAL_SUCCESS";
export const GENERAL_FAIL = "GENERAL_FAIL";

export const DETAIL_GENERAL_REQUEST = "DETAIL_GENERAL_REQUEST";
export const DETAIL_GENERAL_SUCCESS = "DETAIL_GENERAL_SUCCESS";
export const DETAIL_GENERAL_FAIL = "DETAIL_GENERAL_FAIL";
export const DETAIL_GENERAL_RESET = "DETAIL_GENERAL_RESET";

export const DELETE_GENERAL_SUCCESS = "DELETE_GENERAL_SUCCESS";
export const DELETE_GENERAL_FAIL = "DELETE_GENERAL_FAIL";
export const DELETE_GENERAL_RESET = "DELETE_GENERAL_RESET";
export const DELETE_GENERAL_REQUEST = "DELETE_GENERAL_REQUEST";

export const POST_GENERAL_REQUEST = "POST_GENERAL_REQUEST";
export const POST_GENERAL_SUCCESS = "POST_GENERAL_SUCCESS";
export const POST_GENERAL_FAIL = "POST_GENERAL_FAIL";
export const POST_GENERAL_RESET = "POST_GENERAL_RESET";

export const UPDATE_GENERAL_REQUEST = "UPDATE_GENERAL_REQUEST";
export const UPDATE_GENERAL_SUCCESS = "UPDATE_GENERAL_SUCCESS";
export const UPDATE_GENERAL_FAIL = "UPDATE_GENERAL_FAIL";
export const UPDATE_GENERAL_RESET = "UPDATE_GENERAL_RESET";

export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
