export const PAGE_REQUEST = "PAGE_REQUEST";
export const PAGE_SUCCESS = "PAGE_SUCCESS";
export const PAGE_FAIL = "PAGE_FAIL";
export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";
export const POST_PAGE_REQUEST = "POST_PAGE_REQUEST";
export const POST_PAGE_SUCCESS = "POST_PAGE_SUCCESS";
export const POST_PAGE_FAIL = "POST_PAGE_FAIL";
export const POST_PAGE_RESET = "POST_PAGE_RESET";
export const DELETE_PAGE_REQUEST = "DELETE_PAGE_REQUEST";
export const DELETE_PAGE_SUCCESS = "DELETE_PAGE_SUCCESS";
export const DELETE_PAGE_FAIL = "DELETE_PAGE_FAIL";
export const DELETE_PAGE_RESET = "DELETE_PAGE_RESET";
export const DETAIL_PAGE_REQUEST = "DETAIL_PAGE_REQUEST";
export const DETAIL_PAGE_SUCCESS = "DETAIL_PAGE_SUCCESS";
export const DETAIL_PAGE_FAIL = "DETAIL_PAGE_FAIL";
export const DETAIL_PAGE_RESET = "DETAIL_PAGE_RESET";

export const UPDATE_PAGE_REQUEST = "UPDATE_PAGE_REQUEST";
export const UPDATE_PAGE_SUCCESS = "UPDATE_PAGE_SUCCESS";
export const UPDATE_PAGE_FAIL = "UPDATE_PAGE_FAIL";
export const UPDATE_PAGE_RESET = "UPDATE_PAGE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
