export const GET_DATA_PROMPT = "GET_DATA_PROMPT"
export const SUCCESS_GET_DATA_PROMPT = "SUCCESS_GET_DATA_PROMPT"
export const FAIL_GET_DATA_PROMPT = "FAIL_GET_DATA_PROMPT"

export const PUT_DATA_PROMPT = "PUT_DATA_PROMPT"
export const SUCCESS_PUT_DATA_PROMPT = "SUCCESS_PUT_DATA_PROMPT"
export const FAIL_PUT_DATA_PROMPT = "FAIL_PUT_DATA_PROMPT"