export const DATA_REFERENCE_REQUEST = "DATA_REFERENCE_REQUEST";
export const DATA_REFERENCE_SUCCESS = "DATA_REFERENCE_SUCCESS";
export const DATA_REFERENCE_FAIL = "DATA_REFERENCE_FAIL";

export const DETAIL_DATA_REFERENCE_REQUEST = "DETAIL_DATA_REFERENCE_REQUEST";
export const DETAIL_DATA_REFERENCE_SUCCESS = "DETAIL_DATA_REFERENCE_SUCCESS";
export const DETAIL_DATA_REFERENCE_FAIL = "DETAIL_DATA_REFERENCE_FAIL";
export const DETAIL_DATA_REFERENCE_RESET = "DETAIL_DATA_REFERENCE_RESET";

export const DELETE_DATA_REFERENCE_SUCCESS = "DELETE_DATA_REFERENCE_SUCCESS";
export const DELETE_DATA_REFERENCE_FAIL = "DELETE_DATA_REFERENCE_FAIL";
export const DELETE_DATA_REFERENCE_RESET = "DELETE_DATA_REFERENCE_RESET";
export const DELETE_DATA_REFERENCE_REQUEST = "DELETE_DATA_REFERENCE_REQUEST";

export const POST_DATA_REFERENCE_REQUEST = "POST_DATA_REFERENCE_REQUEST";
export const POST_DATA_REFERENCE_SUCCESS = "POST_DATA_REFERENCE_SUCCESS";
export const POST_DATA_REFERENCE_FAIL = "POST_DATA_REFERENCE_FAIL";
export const POST_DATA_REFERENCE_RESET = "POST_DATA_REFERENCE_RESET";

export const UPDATE_DATA_REFERENCE_REQUEST = "UPDATE_DATA_REFERENCE_REQUEST";
export const UPDATE_DATA_REFERENCE_SUCCESS = "UPDATE_DATA_REFERENCE_SUCCESS";
export const UPDATE_DATA_REFERENCE_FAIL = "UPDATE_DATA_REFERENCE_FAIL";
export const UPDATE_DATA_REFERENCE_RESET = "UPDATE_DATA_REFERENCE_RESET";

export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
