export const EXPORT_DATA_REQUEST = "EXPORT_DATA_REQUEST";
export const EXPORT_DATA_SUCCESS = "EXPORT_DATA_SUCCESS";
export const EXPORT_DATA_FAIL = "EXPORT_DATA_FAIL";

export const DETAIL_EXPORT_DATA_REQUEST = "DETAIL_EXPORT_DATA_REQUEST";
export const DETAIL_EXPORT_DATA_SUCCESS = "DETAIL_EXPORT_DATA_SUCCESS";
export const DETAIL_EXPORT_DATA_FAIL = "DETAIL_EXPORT_DATA_FAIL";
export const DETAIL_EXPORT_DATA_RESET = "DETAIL_EXPORT_DATA_RESET";

export const DELETE_EXPORT_DATA_SUCCESS = "DELETE_EXPORT_DATA_SUCCESS";
export const DELETE_EXPORT_DATA_FAIL = "DELETE_EXPORT_DATA_FAIL";
export const DELETE_EXPORT_DATA_RESET = "DELETE_EXPORT_DATA_RESET";
export const DELETE_EXPORT_DATA_REQUEST = "DELETE_EXPORT_DATA_REQUEST";

export const POST_EXPORT_DATA_REQUEST = "POST_EXPORT_DATA_REQUEST";
export const POST_EXPORT_DATA_SUCCESS = "POST_EXPORT_DATA_SUCCESS";
export const POST_EXPORT_DATA_FAIL = "POST_EXPORT_DATA_FAIL";
export const POST_EXPORT_DATA_RESET = "POST_EXPORT_DATA_RESET";

export const UPDATE_EXPORT_DATA_REQUEST = "UPDATE_EXPORT_DATA_REQUEST";
export const UPDATE_EXPORT_DATA_SUCCESS = "UPDATE_EXPORT_DATA_SUCCESS";
export const UPDATE_EXPORT_DATA_FAIL = "UPDATE_EXPORT_DATA_FAIL";
export const UPDATE_EXPORT_DATA_RESET = "UPDATE_EXPORT_DATA_RESET";

export const RELOAD_TABLE = "RELOAD_TABLE";

export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
