export const MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST =
  "MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST";
export const MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS =
  "MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS";
export const MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL =
  "MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL";

export const NEW_MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST =
  "NEW_MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST";
export const NEW_MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS =
  "NEW_MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS";
export const NEW_MASTER_SATUAN_KERJA_PENYELENGGARA_RESET =
  "NEW_MASTER_SATUAN_KERJA_PENYELENGGARA_RESET";
export const NEW_MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL =
  "NEW_MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL";

export const DETAIL_MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST =
  "DETAIL_MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST";
export const DETAIL_MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS =
  "DETAIL_MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS";
export const DETAIL_MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL =
  "DETAIL_MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL";

export const UPDATE_MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST =
  "UPDATE_MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST";
export const UPDATE_MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS =
  "UPDATE_MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS";
export const UPDATE_MASTER_SATUAN_KERJA_PENYELENGGARA_RESET =
  "UPDATE_MASTER_SATUAN_KERJA_PENYELENGGARA_RESET";
export const UPDATE_MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL =
  "UPDATE_MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL";

export const DELETE_MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST =
  "DELETE_MASTER_SATUAN_KERJA_PENYELENGGARA_REQUEST";
export const DELETE_MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS =
  "DELETE_MASTER_SATUAN_KERJA_PENYELENGGARA_SUCCESS";
export const DELETE_MASTER_SATUAN_KERJA_PENYELENGGARA_RESET =
  "DELETE_MASTER_SATUAN_KERJA_PENYELENGGARA_RESET";
export const DELETE_MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL =
  "DELETE_MASTER_SATUAN_KERJA_PENYELENGGARA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
