export const ROLES_REQUEST = "ROLES_REQUEST";
export const ROLES_SUCCESS = "ROLES_SUCCESS";
export const ROLES_FAIL = "ROLES_FAIL";

export const PERMISSION_BY_PARENT = "PERMISSION_BY_PARENT";

export const DETAIL_ROLES_REQUEST = "DETAIL_ROLES_REQUEST";
export const DETAIL_ROLES_SUCCESS = "DETAIL_ROLES_SUCCESS";
export const DETAIL_ROLES_FAIL = "DETAIL_ROLES_FAIL";
export const DETAIL_ROLES_RESET = "DETAIL_ROLES_RESET";

export const DELETE_ROLES_SUCCESS = "DELETE_ROLES_SUCCESS";
export const DELETE_ROLES_FAIL = "DELETE_ROLES_FAIL";
export const DELETE_ROLES_RESET = "DELETE_ROLES_RESET";
export const DELETE_ROLES_REQUEST = "DELETE_ROLES_REQUEST";

export const POST_ROLES_REQUEST = "POST_ROLES_REQUEST";
export const POST_ROLES_SUCCESS = "POST_ROLES_SUCCESS";
export const POST_ROLES_FAIL = "POST_ROLES_FAIL";
export const POST_ROLES_RESET = "POST_ROLES_RESET";

export const UPDATE_ROLES_REQUEST = "UPDATE_ROLES_REQUEST";
export const UPDATE_ROLES_SUCCESS = "UPDATE_ROLES_SUCCESS";
export const UPDATE_ROLES_FAIL = "UPDATE_ROLES_FAIL";
export const UPDATE_ROLES_RESET = "UPDATE_ROLES_RESET";

export const RELOAD_TABLE = "RELOAD_TABLE";

export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";

export const GET_SIDEBAR = "GET_SIDEBAR";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
