export const ROLE_REQUEST = "ROLE_REQUEST";
export const ROLE_SUCCESS = "ROLE_SUCCESS";
export const ROLE_FAIL = "ROLE_FAIL";

export const NEW_ROLE_REQUEST = "NEW_ROLE_REQUEST";
export const NEW_ROLE_SUCCESS = "NEW_ROLE_SUCCESS";
export const NEW_ROLE_RESET = "NEW_ROLE_RESET";
export const NEW_ROLE_FAIL = "NEW_ROLE_FAIL";

export const DETAIL_ROLE_REQUEST = "DETAIL_ROLE_REQUEST";
export const DETAIL_ROLE_SUCCESS = "DETAIL_ROLE_SUCCESS";
export const DETAIL_ROLE_FAIL = "DETAIL_ROLE_FAIL";

export const UPDATE_ROLE_REQUEST = "UPDATE_ROLE_REQUEST";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_RESET = "UPDATE_ROLE_RESET";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";

export const DELETE_ROLE_REQUEST = "DELETE_ROLE_REQUEST";
export const DELETE_ROLE_SUCCESS = "DELETE_ROLE_SUCCESS";
export const DELETE_ROLE_RESET = "DELETE_ROLE_RESET";
export const DELETE_ROLE_FAIL = "DELETE_ROLE_FAIL";

export const DETAIL_ONE_ROLE_REQUEST = "DETAIL_ONE_ROLE_REQUEST";
export const DETAIL_ONE_ROLE_SUCCESS = "DETAIL_ONE_ROLE_SUCCESS";
export const DETAIL_ONE_ROLE_FAIL = "DETAIL_ONE_ROLE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
