export const UNIT_WORK_REQUEST = "UNIT_WORK_REQUEST";
export const UNIT_WORK_SUCCESS = "UNIT_WORK_SUCCESS";
export const UNIT_WORK_FAIL = "UNIT_WORK_FAIL";

export const DETAIL_UNIT_WORK_REQUEST = "DETAIL_UNIT_WORK_REQUEST";
export const DETAIL_UNIT_WORK_SUCCESS = "DETAIL_UNIT_WORK_SUCCESS";
export const DETAIL_UNIT_WORK_FAIL = "DETAIL_UNIT_WORK_FAIL";
export const DETAIL_UNIT_WORK_RESET = "DETAIL_UNIT_WORK_RESET";

export const DELETE_UNIT_WORK_SUCCESS = "DELETE_UNIT_WORK_SUCCESS";
export const DELETE_UNIT_WORK_FAIL = "DELETE_UNIT_WORK_FAIL";
export const DELETE_UNIT_WORK_RESET = "DELETE_UNIT_WORK_RESET";
export const DELETE_UNIT_WORK_REQUEST = "DELETE_UNIT_WORK_REQUEST";

export const POST_UNIT_WORK_REQUEST = "POST_UNIT_WORK_REQUEST";
export const POST_UNIT_WORK_SUCCESS = "POST_UNIT_WORK_SUCCESS";
export const POST_UNIT_WORK_FAIL = "POST_UNIT_WORK_FAIL";
export const POST_UNIT_WORK_RESET = "POST_UNIT_WORK_RESET";

export const UPDATE_UNIT_WORK_REQUEST = "UPDATE_UNIT_WORK_REQUEST";
export const UPDATE_UNIT_WORK_SUCCESS = "UPDATE_UNIT_WORK_SUCCESS";
export const UPDATE_UNIT_WORK_FAIL = "UPDATE_UNIT_WORK_FAIL";
export const UPDATE_UNIT_WORK_RESET = "UPDATE_UNIT_WORK_RESET";

export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
