export const ZONASI_REQUEST = "ZONASI_REQUEST";
export const ZONASI_SUCCESS = "ZONASI_SUCCESS";
export const ZONASI_FAIL = "ZONASI_FAIL";

export const DETAIL_ZONASI_REQUEST = "DETAIL_ZONASI_REQUEST";
export const DETAIL_ZONASI_SUCCESS = "DETAIL_ZONASI_SUCCESS";
export const DETAIL_ZONASI_FAIL = "DETAIL_ZONASI_FAIL";
export const DETAIL_ZONASI_RESET = "DETAIL_ZONASI_RESET";

export const DELETE_ZONASI_SUCCESS = "DELETE_ZONASI_SUCCESS";
export const DELETE_ZONASI_FAIL = "DELETE_ZONASI_FAIL";
export const DELETE_ZONASI_RESET = "DELETE_ZONASI_RESET";
export const DELETE_ZONASI_REQUEST = "DELETE_ZONASI_REQUEST";

export const POST_ZONASI_REQUEST = "POST_ZONASI_REQUEST";
export const POST_ZONASI_SUCCESS = "POST_ZONASI_SUCCESS";
export const POST_ZONASI_FAIL = "POST_ZONASI_FAIL";
export const POST_ZONASI_RESET = "POST_ZONASI_RESET";

export const UPDATE_ZONASI_REQUEST = "UPDATE_ZONASI_REQUEST";
export const UPDATE_ZONASI_SUCCESS = "UPDATE_ZONASI_SUCCESS";
export const UPDATE_ZONASI_FAIL = "UPDATE_ZONASI_FAIL";
export const UPDATE_ZONASI_RESET = "UPDATE_ZONASI_RESET";

export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
