export const KERJASAMA_REQUEST = "KERJASAMA_REQUEST";
export const KERJASAMA_SUCCESS = "KERJASAMA_SUCCESS";
export const KERJASAMA_FAIL = "KERJASAMA_FAIL";

// export const NEW_ARTIKEL_REQUEST = "NEW_ARTIKEL_REQUEST";
// export const NEW_ARTIKEL_SUCCESS = "NEW_ARTIKEL_SUCCESS";
// export const NEW_ARTIKEL_RESET = "NEW_ARTIKEL_RESET";
// export const NEW_ARTIKEL_FAIL = "NEW_ARTIKEL_FAIL";

// export const DETAIL_ARTIKEL_REQUEST = "DETAIL_ARTIKEL_REQUEST";
// export const DETAIL_ARTIKEL_SUCCESS = "DETAIL_ARTIKEL_SUCCESS";
// export const DETAIL_ARTIKEL_FAIL = "DETAIL_ARTIKEL_FAIL";

// export const UPDATE_ARTIKEL_REQUEST = "UPDATE_ARTIKEL_REQUEST";
// export const UPDATE_ARTIKEL_SUCCESS = "UPDATE_ARTIKEL_SUCCESS";
// export const UPDATE_ARTIKEL_RESET = "UPDATE_ARTIKEL_RESET";
// export const UPDATE_ARTIKEL_FAIL = "UPDATE_ARTIKEL_FAIL";

// export const DELETE_ARTIKEL_REQUEST = "DELETE_ARTIKEL_REQUEST";
// export const DELETE_ARTIKEL_SUCCESS = "DELETE_ARTIKEL_SUCCESS";
// export const DELETE_ARTIKEL_RESET = "DELETE_ARTIKEL_RESET";
// export const DELETE_ARTIKEL_FAIL = "DELETE_ARTIKEL_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
