export const MANAGEMENT_COOPORATION_REQUEST = "MANAGEMENT_COOPORATION_REQUEST";
export const MANAGEMENT_COOPORATION_SUCCESS = "MANAGEMENT_COOPORATION_SUCCESS";
export const MANAGEMENT_COOPORATION_FAIL = "MANAGEMENT_COOPORATION_FAIL";
export const LIST_MITRA_REQUEST = "LIST_MITRA_REQUEST";
export const LIST_MITRA_SUCCESS = "LIST_MITRA_SUCCESS";
export const LIST_MITRA_FAIL = "LIST_MITRA_FAIL";
export const LIST_COOPERATION_REQUEST = "LIST_COOPERATION_REQUEST";
export const LIST_COOPERATION_SUCCESS = "LIST_COOPERATION_SUCCESS";
export const LIST_COOPERATION_FAIL = "LIST_COOPERATION_FAIL";
export const LIST_STATUS_REQUEST = "LIST_STATUS_REQUEST";
export const LIST_STATUS_SUCCESS = "LIST_STATUS_SUCCESS";
export const LIST_STATUS_FAIL = "LIST_STATUS_FAIL";
export const SEARCH_M_COORPORATION = "SEARCH_M_COORPORATION";
export const SET_PAGE_M = "SET_PAGE_M";
export const SET_VALUE_MITRA_M = "SET_VALUE_MITRA_M";
export const SET_VALUE_STATUS_M = "SET_VALUE_STATUS_M";
export const SET_VALUE_CARD_M = "SET_VALUE_CARD_M";
export const SET_VALUE_KERJA_SAMA_M = "SET_VALUE_KERJA_SAMA_M";
export const LIMIT_CONFIGURATION_M = "LIMIT_CONFIGURATION_M";
//
export const SET_NAME_LEMBAGA = "SET_NAME_LEMBAGA";
export const SUCCESS_GET_EMAIL = "SUCCESS_GET_EMAIL";
export const FAIL_GET_EMAIL = "FAIL_GET_EMAIL";
//
// export const COOPERATION_ACTIVE_REQUEST = "COOPERATION_ACTIVE_REQUEST";
// export const COOPERATION_ACTIVE_SUCCESS = "COOPERATION_ACTIVE_SUCCESS";
// export const COOPERATION_ACTIVE_FAIL = "COOPERATION_ACTIVE_FAIL";
//
export const COOPERATION_PENGAJUAN_REQUEST = "COOPERATION_PENGAJUAN_REQUEST";
export const COOPERATION_PENGAJUAN_SUCCESS = "COOPERATION_PENGAJUAN_SUCCESS";
export const COOPERATION_PENGAJUAN_FAIL = "COOPERATION_PENGAJUAN_FAIL";
//
export const GET_COOPERTAION_ACTIVE_SELECT = "GET_COOPERTAION_ACTIVE_SELECT";
export const SUCCESS_COOPERTAION_ACTIVE_SELECT =
  "SUCCESS_COOPERTAION_ACTIVE_SELECT";
export const FAIL_COOPERTAION_ACTIVE_SELECT = "FAIL_COOPERTAION_ACTIVE_SELECT";
//
export const GET_COOPERTAION_ACTIVE_SELECT_BY_ID =
  "GET_COOPERTAION_ACTIVE_SELECT_BY_ID";
export const SUCCESS_COOPERTAION_ACTIVE_SELECT_BY_ID =
  "SUCCESS_COOPERTAION_ACTIVE_SELECT_BY_ID";
export const FAIL_COOPERTAION_ACTIVE_SELECT_BY_ID =
  "FAIL_COOPERTAION_ACTIVE_SELECT_BY_ID";
export const CHANGE_COOPERTAION_ACTIVE_SELECT_BY_ID =
  "CHANGE_COOPERTAION_ACTIVE_SELECT_BY_ID";
//
export const SUCCESS_DELETE_COOPERATION_M = "SUCCESS_DELETE_COOPERATION_M";
export const SUCCESS_GET_SINGLE_COOPERATION_M =
  "SUCCESS_GET_SINGLE_COOPERATION_M";
export const CHANGE_STATUS_LIST_M = "CHANGE_STATUS_LIST_M";
export const CANCEL_CHANGE_CATEGORY = "CANCEL_CHANGE_CATEGORY";
export const CANCEL_CHANGE_EMAIL = "CANCEL_CHANGE_EMAIL";
export const RELOAD_TABLE = "RELOAD_TABLE";

// export const COOPERATION_NONAKTIF_REQUEST = "COOPERATION_NONAKTIF_REQUEST";
// export const COOPERATION_NONAKTIF_SUCCESS = "COOPERATION_NONAKTIF_SUCCESS";
// export const COOPERATION_NONAKTIF_FAIL = "COOPERATION_NONAKTIF_FAIL";
