export const MITRA_REQUEST = "MITRA_REQUEST";
export const MITRA_SUCCESS = "MITRA_SUCCESS";
export const MITRA_FAIL = "MITRA_FAIL";

export const NEW_MITRA_REQUEST = "NEW_MITRA_REQUEST";
export const NEW_MITRA_SUCCESS = "NEW_MITRA_SUCCESS";
export const NEW_MITRA_RESET = "NEW_MITRA_RESET";
export const NEW_MITRA_FAIL = "NEW_MITRA_FAIL";
