export const MITRA_REQUEST = "MITRA_REQUEST";
export const MITRA_SUCCESS = "MITRA_SUCCESS";
export const MITRA_FAIL = "MITRA_FAIL";
export const SEARCH_BY_KEY = "SEARCH_BY_KEY";
export const SEARCH_BY_KEY_DETAIL = "SEARCH_BY_KEY_DETAIL";
export const SUCESS_DELETE_MITRA = "SUCESS_DELETE_MITRA";
export const SUCESS_PROVINCE = "SUCESS_PROVINCE";
export const SET_PAGE_M = "SET_PAGE_M";
export const SET_PAGE_M_DETAIL = "SET_PAGE_M_DETAIL";
export const SET_LIMIT = "SET_LIMIT";
export const SET_LIMIT_DETAIL = "SET_LIMIT_DETAIL";
export const CANCEL_CHANGE_PROVINCES = "CANCEL_CHANGE_PROVINCES";
// ==============================mitra detail
export const MITRA_REQUEST_DETAIL = "MITRA_REQUEST_DETAIL";
export const MITRA_SUCCESS_DETAIL = "MITRA_SUCCESS_DETAIL";
export const MITRA_FAIL_DETAIL = "MITRA_FAIL_DETAIL";
export const LIST_COOPERATION_SUCCESS_DETAIL =
  "LIST_COOPERATION_SUCCESS_DETAIL";
export const LIST_STATUS_SUCCESS_DETAIL = "LIST_STATUS_SUCCESS_DETAIL";
export const SET_VALUE_KERJA_SAMA_M_DETAIL = "SET_VALUE_KERJA_SAMA_M_DETAIL";
export const SET_VALUE_STATUS_M_DETAIL = "SET_VALUE_STATUS_M_DETAIL";

export const RELOAD_TABLE_DETAIL = "RELOAD_TABLE_DETAIL";
export const SUCCESS_DELETE_COOPERATION_M_DETAIL =
  "SUCCESS_DELETE_COOPERATION_M_DETAIL";
export const CHANGE_STATUS_LIST_M_DETAIL = "CHANGE_STATUS_LIST_M_DETAIL";
