export const MK_COOPORATION_REQUEST = "MK_COOPORATION_REQUEST";
export const MK_COOPORATION_SUCCESS = "MK_COOPORATION_SUCCESS";
export const MK_COOPORATION_FAIL = "MK_COOPORATION_FAIL";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";
export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SUCCESS_GET_SINGLE_COOPORATION = "SUCCESS_GET_SINGLE_COOPORATION";
export const DELETE_COOPORATION_REQUEST = "DELETE_COOPORATION_REQUEST";
export const SUCCESS_DELETE_COOPORATION_REQUEST =
  "SUCCESS_DELETE_COOPORATION_REQUEST";
export const SUCCESS_CHANGE_STATUS_LIST = "SUCCESS_CHANGE_STATUS_LIST";
export const SET_PAGE = "SET_PAGE";
