export const FETCH_PARTNERSHIP_PERMISSION_REQUEST = "FETCH_PARTNERSHIP_PERMISSION_REQUEST";
export const FETCH_PARTNERSHIP_PERMISSION_SUCCESS = "FETCH_PARTNERSHIP_PERMISSION_SUCCESS";
export const FETCH_PARTNERSHIP_PERMISSION_FAIL = "FETCH_PARTNERSHIP_PERMISSION_FAIL";

export const CLEAR_ERRORS = 'CLEAR_ERRORS'