export const TANDA_TANGAN_REQUEST = "TANDA_TANGAN_REQUEST";
export const TANDA_TANGAN_SUCCESS = "TANDA_TANGAN_SUCCESS";
export const TANDA_TANGAN_FAIL = "TANDA_TANGAN_FAIL";

export const NEW_TANDA_TANGAN_REQUEST = "NEW_TANDA_TANGAN_REQUEST";
export const NEW_TANDA_TANGAN_SUCCESS = "NEW_TANDA_TANGAN_SUCCESS";
export const NEW_TANDA_TANGAN_RESET = "NEW_TANDA_TANGAN_RESET";
export const NEW_TANDA_TANGAN_FAIL = "NEW_TANDA_TANGAN_FAIL";

export const DELETE_TANDA_TANGAN_REQUEST = "DELETE_TANDA_TANGAN_REQUEST";
export const DELETE_TANDA_TANGAN_SUCCESS = "DELETE_TANDA_TANGAN_SUCCESS";
export const DELETE_TANDA_TANGAN_FAIL = "DELETE_TANDA_TANGAN_FAIL";
export const DELETE_TANDA_TANGAN_RESET = "DELETE_TANDA_TANGAN_RESET";

export const UPDATE_TANDA_TANGAN_REQUEST = "UPDATE_TANDA_TANGAN_REQUEST";
export const UPDATE_TANDA_TANGAN_SUCCESS = "UPDATE_TANDA_TANGAN_SUCCESS";
export const UPDATE_TANDA_TANGAN_FAIL = "UPDATE_TANDA_TANGAN_FAIL";
export const UPDATE_TANDA_TANGAN_RESET = "UPDATE_TANDA_TANGAN_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
