export const TANDA_TANGAN_REQUEST = "TANDA_TANGAN_REQUEST";
export const TANDA_TANGAN_SUCCESS = "TANDA_TANGAN_SUCCESS";
export const TANDA_TANGAN_FAIL = "TANDA_TANGAN_FAIL";
export const RELOAD_TABLE = "RELOAD_TABLE";
export const SET_PAGE_M_TD = "SET_PAGE_M_TD";
export const SET_LIMIT_TD = "SET_LIMIT_TD";
export const SUCESS_DELETE_TD = "SUCESS_DELETE_TD";
export const SEARCH_BY_KEY_TTD = "SEARCH_BY_KEY_TTD";
