export const COOPERATION_REQUEST = "COOPERATION_REQUEST";
export const COOPERATION_SUCCESS = "COOPERATION_SUCCESS";
export const COOPERATION_ERROR = "COOPERATION_ERROR";
export const FAIL_COOPERTAION_ACTIVE_SELECT_USER =
  "FAIL_COOPERTAION_ACTIVE_SELECT_USER";
export const SUCCESS_COOPERTAION_ACTIVE_SELECT_USER =
  "SUCCESS_COOPERTAION_ACTIVE_SELECT_USER";
export const CHANGE_COOPERTAION_ACTIVE_SELECT_BY_ID_USER =
  "CHANGE_COOPERTAION_ACTIVE_SELECT_BY_ID_USER";
export const SUCCESS_COOPERTAION_ACTIVE_SELECT_BY_ID_USER =
  "SUCCESS_COOPERTAION_ACTIVE_SELECT_BY_ID_USER";
export const FAIL_COOPERTAION_ACTIVE_SELECT_BY_ID_USER =
  "FAIL_COOPERTAION_ACTIVE_SELECT_BY_ID_USER";

//
export const SET_PAGE_U = "SET_PAGE_U";
