export const COOPERATION_REQUEST = "COOPERATION_REQUEST";
export const COOPERATION_SUCCESS = "COOPERATION_SUCCESS";
export const COOPERATION_ERROR = "COOPERATION_ERROR";
export const SET_PAGE_U = "SET_PAGE_U";
