export const COOPERATION_REQUEST = "COOPERATION_REQUEST";
export const COOPERATION_SUCCESS = "COOPERATION_SUCCESS";
export const COOPERATION_ERROR = "COOPERATION_ERROR";
export const FAIL_COOPERTAION_ACTIVE_SELECT_USER =
  "FAIL_COOPERTAION_ACTIVE_SELECT_USER";
export const SUCCESS_COOPERTAION_ACTIVE_SELECT_USER =
  "SUCCESS_COOPERTAION_ACTIVE_SELECT_USER";
export const CHANGE_COOPERTAION_ACTIVE_SELECT_BY_ID_USER =
  "CHANGE_COOPERTAION_ACTIVE_SELECT_BY_ID_USER";
export const SUCCESS_COOPERTAION_ACTIVE_SELECT_BY_ID_USER =
  "SUCCESS_COOPERTAION_ACTIVE_SELECT_BY_ID_USER";
export const FAIL_COOPERTAION_ACTIVE_SELECT_BY_ID_USER =
  "FAIL_COOPERTAION_ACTIVE_SELECT_BY_ID_USER";
export const SEARCH_M_COORPORATION = "SEARCH_M_COORPORATION";
export const LIST_STATUS_REQUEST = "LIST_STATUS_REQUEST";
export const LIST_STATUS_SUCCESS = "LIST_STATUS_SUCCESS";
export const LIST_STATUS_FAIL = "LIST_STATUS_FAIL";
export const RESET_VALUE_SORTIR = "RESET_VALUE_SORTIR";
export const SET_VALUE_STATUS_M = "SET_VALUE_STATUS_M";
export const SET_VALUE_KERJA_SAMA_M = "SET_VALUE_KERJA_SAMA_M";
export const LIST_COOPERATION_REQUEST = "LIST_COOPERATION_REQUEST";
export const LIST_COOPERATION_FAIL = "LIST_COOPERATION_FAIL";
export const LIST_COOPERATION_SUCCESS = "LIST_COOPERATION_SUCCESS";
export const SET_VALUE_CARD_M = "SET_VALUE_CARD_M";
export const LIMIT_CONFIGURATION_M = "LIMIT_CONFIGURATION_M";

//
export const SET_PAGE_U = "SET_PAGE_U";
