export const ADMIN_SITE_REQUEST = "ADMIN_SITE_REQUEST";
export const ADMIN_SITE_SUCCESS = "ADMIN_SITE_SUCCESS";
export const ADMIN_SITE_FAIL = "ADMIN_SITE_FAIL";

export const GET_LIST_ADMIN_SITE_REQUEST = "GET_LIST_ADMIN_SITE_REQUEST";
export const GET_LIST_ADMIN_SITE_SUCCESS = "GET_LIST_ADMIN_SITE_SUCCESS";
export const GET_LIST_ADMIN_SITE_FAIL = "GET_LIST_ADMIN_SITE_FAIL";

export const DETAIL_ADMIN_SITE_REQUEST = "DETAIL_ADMIN_SITE_REQUEST";
export const DETAIL_ADMIN_SITE_SUCCESS = "DETAIL_ADMIN_SITE_SUCCESS";
export const DETAIL_ADMIN_SITE_FAIL = "DETAIL_ADMIN_SITE_FAIL";
export const DETAIL_ADMIN_SITE_RESET = "DETAIL_ADMIN_SITE_RESET";

export const DELETE_ADMIN_SITE_SUCCESS = "DELETE_ADMIN_SITE_SUCCESS";
export const DELETE_ADMIN_SITE_FAIL = "DELETE_ADMIN_SITE_FAIL";
export const DELETE_ADMIN_SITE_RESET = "DELETE_ADMIN_SITE_RESET";
export const DELETE_ADMIN_SITE_REQUEST = "DELETE_ADMIN_SITE_REQUEST";

export const POST_ADMIN_SITE_REQUEST = "POST_ADMIN_SITE_REQUEST";
export const POST_ADMIN_SITE_SUCCESS = "POST_ADMIN_SITE_SUCCESS";
export const POST_ADMIN_SITE_FAIL = "POST_ADMIN_SITE_FAIL";
export const POST_ADMIN_SITE_RESET = "POST_ADMIN_SITE_RESET";

export const UPDATE_ADMIN_SITE_REQUEST = "UPDATE_ADMIN_SITE_REQUEST";
export const UPDATE_ADMIN_SITE_SUCCESS = "UPDATE_ADMIN_SITE_SUCCESS";
export const UPDATE_ADMIN_SITE_FAIL = "UPDATE_ADMIN_SITE_FAIL";
export const UPDATE_ADMIN_SITE_RESET = "UPDATE_ADMIN_SITE_RESET";

export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
