export const MITRA_SITE_REQUEST = "MITRA_SITE_REQUEST";
export const MITRA_SITE_SUCCESS = "MITRA_SITE_SUCCESS";
export const MITRA_SITE_FAIL = "MITRA_SITE_FAIL";

export const GET_LIST_MITRA_SITE_REQUEST = "GET_LIST_MITRA_SITE_REQUEST";
export const GET_LIST_MITRA_SITE_SUCCESS = "GET_LIST_MITRA_SITE_SUCCESS";
export const GET_LIST_MITRA_SITE_FAIL = "GET_LIST_MITRA_SITE_FAIL";

export const DETAIL_MITRA_SITE_REQUEST = "DETAIL_MITRA_SITE_REQUEST";
export const DETAIL_MITRA_SITE_SUCCESS = "DETAIL_MITRA_SITE_SUCCESS";
export const DETAIL_MITRA_SITE_FAIL = "DETAIL_MITRA_SITE_FAIL";
export const DETAIL_MITRA_SITE_RESET = "DETAIL_MITRA_SITE_RESET";

export const DELETE_MITRA_SITE_SUCCESS = "DELETE_MITRA_SITE_SUCCESS";
export const DELETE_MITRA_SITE_FAIL = "DELETE_MITRA_SITE_FAIL";
export const DELETE_MITRA_SITE_RESET = "DELETE_MITRA_SITE_RESET";
export const DELETE_MITRA_SITE_REQUEST = "DELETE_MITRA_SITE_REQUEST";

export const POST_MITRA_SITE_REQUEST = "POST_MITRA_SITE_REQUEST";
export const POST_MITRA_SITE_SUCCESS = "POST_MITRA_SITE_SUCCESS";
export const POST_MITRA_SITE_FAIL = "POST_MITRA_SITE_FAIL";
export const POST_MITRA_SITE_RESET = "POST_MITRA_SITE_RESET";

export const UPDATE_MITRA_SITE_REQUEST = "UPDATE_MITRA_SITE_REQUEST";
export const UPDATE_MITRA_SITE_SUCCESS = "UPDATE_MITRA_SITE_SUCCESS";
export const UPDATE_MITRA_SITE_FAIL = "UPDATE_MITRA_SITE_FAIL";
export const UPDATE_MITRA_SITE_RESET = "UPDATE_MITRA_SITE_RESET";

export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
