export const LIST_PESERTA_REQUEST = "LIST_PESERTA_REQUEST";
export const LIST_PESERTA_SUCCESS = "LIST_PESERTA_SUCCESS";
export const LIST_PESERTA_FAIL = "LIST_PESERTA_FAIL";
export const DETAIL_PESERTA_REQUEST = "DETAIL_PESERTA_REQUEST";
export const DETAIL_PESERTA_SUCCESS = "DETAIL_PESERTA_SUCCESS";
export const DETAIL_PESERTA_FAIL = "DETAIL_PESERTA_FAIL";
export const LIST_PELATIHAN_BY_PESERTA_REQUEST =
  "LIST_PELATIHAN_BY_PESERTA_REQUEST";
export const LIST_PELATIHAN_BY_PESERTA_SUCCESS =
  "LIST_PELATIHAN_BY_PESERTA_SUCCESS";
export const LIST_PELATIHAN_BY_PESERTA_FAIL = "LIST_PELATIHAN_BY_PESERTA_FAIL";
export const DETAIL_PELATIHAN_PESERTA_REQUEST =
  "DETAIL_PELATIHAN_PESERTA_REQUEST";
export const DETAIL_PELATIHAN_PESERTA_SUCCESS =
  "DETAIL_PELATIHAN_PESERTA_SUCCESS";
export const DETAIL_PELATIHAN_PESERTA_FAIL = "DETAIL_PELATIHAN_PESERTA_FAIL";
export const UPDATE_DATA_PESERTA_REQUEST = "UPDATE_DATA_PESERTA_REQUEST";
export const UPDATE_DATA_PESERTA_SUCCESS = "UPDATE_DATA_PESERTA_SUCCESS";
export const UPDATE_DATA_PESERTA_FAIL = "UPDATE_DATA_PESERTA_FAIL";
export const SET_PAGE = "SET_PAGE";
export const SEARCH_COORPORATION = "SEARCH_COORPORATION";
export const LIMIT_CONFIGURATION = "LIMIT_CONFIGURATION";

export const LIST_PELATIHAN_PAGINATION_REQUEST = "LIST_PELATIHAN_PAGINATION_REQUEST";
export const LIST_PELATIHAN_PAGINATION_SUCCESS = "LIST_PELATIHAN_PAGINATION_SUCCESS";
export const LIST_PELATIHAN_PAGINATION_FAIL = "LIST_PELATIHAN_PAGINATION_FAIL";
