export const BEASISWA_KANDIDAT_REQUEST = "BEASISWA_KANDIDAT_REQUEST";
export const BEASISWA_KANDIDAT_SUCCESS = "BEASISWA_KANDIDAT_SUCCESS";
export const BEASISWA_KANDIDAT_FAIL = "BEASISWA_KANDIDAT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
