export const BEASISWA_KANDIDAT_REQUEST = "BEASISWA_KANDIDAT_REQUEST";
export const BEASISWA_KANDIDAT_SUCCESS = "BEASISWA_KANDIDAT_SUCCESS";
export const BEASISWA_KANDIDAT_FAIL = "BEASISWA_KANDIDAT_FAIL";

export const BEASISWA_FILTER_REQUEST = "BEASISWA_FILTER_REQUEST";
export const BEASISWA_FILTER_SUCCESS = "BEASISWA_FILTER_SUCCESS";
export const BEASISWA_FILTER_FAIL = "BEASISWA_FILTER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
