export const SIMONAS_KANDIDAT_REQUEST = "SIMONAS_KANDIDAT_REQUEST";
export const SIMONAS_KANDIDAT_SUCCESS = "SIMONAS_KANDIDAT_SUCCESS";
export const SIMONAS_KANDIDAT_FAIL = "SIMONAS_KANDIDAT_FAIL";

export const SIMONAS_FILTER_COMPANY_REQUEST = "SIMONAS_FILTER_COMPANY_REQUEST";
export const SIMONAS_FILTER_COMPANY_SUCCESS = "SIMONAS_FILTER_COMPANY_SUCCESS";
export const SIMONAS_FILTER_COMPANY_FAIL = "SIMONAS_FILTER_COMPANY_FAIL";

export const SIMONAS_FILTER_STATUS_REQUEST = "SIMONAS_FILTER_STATUS_REQUEST";
export const SIMONAS_FILTER_STATUS_SUCCESS = "SIMONAS_FILTER_STATUS_SUCCESS";
export const SIMONAS_FILTER_STATUS_FAIL = "SIMONAS_FILTER_STATUS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
