export const SIMONAS_KANDIDAT_REQUEST = "SIMONAS_KANDIDAT_REQUEST";
export const SIMONAS_KANDIDAT_SUCCESS = "SIMONAS_KANDIDAT_SUCCESS";
export const SIMONAS_KANDIDAT_FAIL = "SIMONAS_KANDIDAT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
