export const IS_SHOW_PROFILE = "IS_SHOW_PROFILE";
export const IS_OVERLAY_PROFILE = "IS_OVERLAY_PROFILE";
export const IS_ASSIDE_MOBILE_SIDEBAR = "IS_ASSIDE_MOBILE_SIDEBAR";
export const IS_OVERLAY_SIDEBAR_MOBILE = "IS_OVERLAY_SIDEBAR_MOBILE";
export const IS_MINIMIZE_SIDEBAR = "IS_MINIMIZE_SIDEBAR";
export const IS_ASSIDE_HEADER = "IS_ASSIDE_HEADER";
export const IS_OVERLAY_ASSIDE_HEADER = "IS_OVERLAY_ASSIDE_HEADER";
