// provinsi
export const PROVINSI_REQUEST = "PROVINSI_REQUEST";
export const PROVINSI_SUCCESS = "PROVINSI_SUCCESS";
export const PROVINSI_FAIL = "PROVINSI_FAIL";

// kota
export const KOTA_REQUEST = "KOTA_REQUEST";
export const KOTA_SUCCESS = "KOTA_SUCCESS";
export const KOTA_FAIL = "KOTA_FAIL";

export const GET_SUPERADMIN_PERMISSION_REQUEST =
  "GET_SUPERADMIN_PERMISSION_REQUEST";

export const GET_SUPERADMIN_PERMISSION_SUCCESS =
  "GET_SUPERADMIN_PERMISSION_SUCCESS";

export const GET_SUPERADMIN_PERMISSION_FAIL = "GET_SUPERADMIN_PERMISSION_FAIL";
