// BEASISWA TOTAL PENGGUNA
export const BEASISWA_TOTAL_PENGGUNA_REQUEST =
  "BEASISWA_TOTAL_PENGGUNA_REQUEST";
export const BEASISWA_TOTAL_PENGGUNA_SUCCESS =
  "BEASISWA_TOTAL_PENGGUNA_SUCCESS";
export const BEASISWA_TOTAL_PENGGUNA_FAIL = "BEASISWA_TOTAL_PENGGUNA_FAIL";

// BEASISWA TOTAL PENDAFTAR
export const BEASISWA_TOTAL_PENDAFTAR_REQUEST =
  "BEASISWA_TOTAL_PENDAFTAR_REQUEST";
export const BEASISWA_TOTAL_PENDAFTAR_SUCCESS =
  "BEASISWA_TOTAL_PENDAFTAR_SUCCESS";
export const BEASISWA_TOTAL_PENDAFTAR_FAIL = "BEASISWA_TOTAL_PENDAFTAR_FAIL";

// BEASISWA STATISTIK
export const BEASISWA_STATISTIK_DALAM_REQUEST =
  "BEASISWA_STATISTIK_DALAM_REQUEST";
export const BEASISWA_STATISTIK_DALAM_SUCCESS =
  "BEASISWA_STATISTIK_DALAM_SUCCESS";
export const BEASISWA_STATISTIK_DALAM_FAIL = "BEASISWA_STATISTIK_DALAM_FAIL";

export const BEASISWA_STATISTIK_LUAR_REQUEST =
  "BEASISWA_STATISTIK_LUAR_REQUEST";
export const BEASISWA_STATISTIK_LUAR_SUCCESS =
  "BEASISWA_STATISTIK_LUAR_SUCCESS";
export const BEASISWA_STATISTIK_LUAR_FAIL = "BEASISWA_STATISTIK_LUAR_FAIL";

// BEASISWA MAP PENDAFTAR
export const BEASISWA_MAP_PENDAFTAR_REQUEST = "BEASISWA_MAP_PENDAFTAR_REQUEST";
export const BEASISWA_MAP_PENDAFTAR_SUCCESS = "BEASISWA_MAP_PENDAFTAR_SUCCESS";
export const BEASISWA_MAP_PENDAFTAR_FAIL = "BEASISWA_MAP_PENDAFTAR_FAIL";

// BEASISWA PROVINSI
export const BEASISWA_PROVINSI_PENDAFTAR_REQUEST =
  "BEASISWA_PROVINSI_PENDAFTAR_REQUEST";
export const BEASISWA_PROVINSI_PENDAFTAR_SUCCESS =
  "BEASISWA_PROVINSI_PENDAFTAR_SUCCESS";
export const BEASISWA_PROVINSI_PENDAFTAR_FAIL =
  "BEASISWA_PROVINSI_PENDAFTAR_FAIL";

export const BEASISWA_PROVINSI_AWARDEE_REQUEST =
  "BEASISWA_PROVINSI_AWARDEE_REQUEST";
export const BEASISWA_PROVINSI_AWARDEE_SUCCESS =
  "BEASISWA_PROVINSI_AWARDEE_SUCCESS";
export const BEASISWA_PROVINSI_AWARDEE_FAIL = "BEASISWA_PROVINSI_AWARDEE_FAIL";

// BEASISWA UNIVERSITAS
export const BEASISWA_UNIVERSITAS_DALAM_REQUEST =
  "BEASISWA_UNIVERSITAS_DALAM_REQUEST";
export const BEASISWA_UNIVERSITAS_DALAM_SUCCESS =
  "BEASISWA_UNIVERSITAS_DALAM_SUCCESS";
export const BEASISWA_UNIVERSITAS_DALAM_FAIL =
  "BEASISWA_UNIVERSITAS_DALAM_FAIL";

export const BEASISWA_UNIVERSITAS_LUAR_REQUEST =
  "BEASISWA_UNIVERSITAS_LUAR_REQUEST";
export const BEASISWA_UNIVERSITAS_LUAR_SUCCESS =
  "BEASISWA_UNIVERSITAS_LUAR_SUCCESS";
export const BEASISWA_UNIVERSITAS_LUAR_FAIL = "BEASISWA_UNIVERSITAS_LUAR_FAIL";

// BEASISWA ALUMNI
export const BEASISWA_AWARDEE_REQUEST = "BEASISWA_AWARDEE_REQUEST";
export const BEASISWA_AWARDEE_SUCCESS = "BEASISWA_AWARDEE_SUCCESS";
export const BEASISWA_AWARDEE_FAIL = "BEASISWA_AWARDEE_FAIL";

export const BEASISWA_ALUMNI_REQUEST = "BEASISWA_ALUMNI_REQUEST";
export const BEASISWA_ALUMNI_SUCCESS = "BEASISWA_ALUMNI_SUCCESS";
export const BEASISWA_ALUMNI_FAIL = "BEASISWA_ALUMNI_FAIL";

// BEASISWA YEAR
export const BEASISWA_YEAR_REQUEST = "BEASISWA_YEAR_REQUEST";
export const BEASISWA_YEAR_SUCCESS = "BEASISWA_YEAR_SUCCESS";
export const BEASISWA_YEAR_FAIL = "BEASISWA_YEAR_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
