// TOTAL PENGGUNA
export const DTS_TOTAL_PENGGUNA_REQUEST = "DTS_TOTAL_PENGGUNA_REQUEST";
export const DTS_TOTAL_PENGGUNA_SUCCESS = "DTS_TOTAL_PENGGUNA_SUCCESS";
export const DTS_TOTAL_PENGGUNA_FAIL = "DTS_TOTAL_PENGGUNA_FAIL";

// STATISTIK PESERTA
export const DTS_STATISTIK_AKADEMI_PESERTA_REQUEST =
  "DTS_STATISTIK_AKADEMI_PESERTA_REQUEST";
export const DTS_STATISTIK_AKADEMI_PESERTA_SUCCESS =
  "DTS_STATISTIK_AKADEMI_PESERTA_SUCCESS";
export const DTS_STATISTIK_AKADEMI_PESERTA_FAIL =
  "DTS_STATISTIK_AKADEMI_PESERTA_FAIL";

export const DTS_STATISTIK_AKADEMI_PENDAFTAR_REQUEST =
  "DTS_STATISTIK_AKADEMI_PENDAFTAR_REQUEST";
export const DTS_STATISTIK_AKADEMI_PENDAFTAR_SUCCESS =
  "DTS_STATISTIK_AKADEMI_PENDAFTAR_SUCCESS";
export const DTS_STATISTIK_AKADEMI_PENDAFTAR_FAIL =
  "DTS_STATISTIK_AKADEMI_PESERTA_FAIL";

//   STATISTIK MITRA
export const DTS_STATISTIK_MITRA_PENDAFTAR_REQUEST =
  "DTS_STATISTIK_MITRA_PENDAFTAR_REQUEST";
export const DTS_STATISTIK_MITRA_PENDAFTAR_SUCCESS =
  "DTS_STATISTIK_MITRA_PENDAFTAR_SUCCESS";
export const DTS_STATISTIK_MITRA_PENDAFTAR_FAIL =
  "DTS_STATISTIK_MITRA_PESERTA_FAIL";

export const DTS_STATISTIK_MITRA_PESERTA_REQUEST =
  "DTS_STATISTIK_MITRA_PESERTA_REQUEST";
export const DTS_STATISTIK_MITRA_PESERTA_SUCCESS =
  "DTS_STATISTIK_MITRA_PESERTA_SUCCESS";
export const DTS_STATISTIK_MITRA_PESERTA_FAIL =
  "DTS_STATISTIK_MITRA_PESERTA_FAIL";

//   TABLE PENDAFTARAN DIBUKA
export const DTS_LIST_PENDAFTARAN_REQUEST = "DTS_LIST_PENDAFTARAN_REQUEST";
export const DTS_LIST_PENDAFTARAN_SUCCESS = "DTS_LIST_PENDAFTARAN_SUCCESS";
export const DTS_LIST_PENDAFTARAN_FAIL = "DTS_LIST_PENDAFTARAN_FAIL";

// PENYEBARAN PESERTA WILAYAH
export const DTS_LIST_PESERTA_WILAYAH_REQUEST =
  "DTS_LIST_PESERTA_WILAYAH_REQUEST";
export const DTS_LIST_PESERTA_WILAYAH_SUCCESS =
  "DTS_LIST_PESERTA_WILAYAH_SUCCESS";
export const DTS_LIST_PESERTA_WILAYAH_FAIL = "DTS_LIST_PESERTA_WILAYAH_FAIL";

// PROVINSI PENDAFTAR || PESERTA
export const DTS_PROVINSI_PENDAFTAR_REQUEST = "DTS_PROVINSI_PENDAFTAR_REQUEST";
export const DTS_PROVINSI_PENDAFTAR_SUCCESS = "DTS_PROVINSI_PENDAFTAR_SUCCESS";
export const DTS_PROVINSI_PENDAFTAR_FAIL = "DTS_PROVINSI_PENDAFTAR_FAIL";

export const DTS_PROVINSI_PESERTA_REQUEST = "DTS_PROVINSI_PESERTA_REQUEST";
export const DTS_PROVINSI_PESERTA_SUCCESS = "DTS_PROVINSI_PESERTA_SUCCESS";
export const DTS_PROVINSI_PESERTA_FAIL = "DTS_PROVINSI_PESERTA_FAIL";

// UMUR PENDAFTAR || PESERTA
export const DTS_UMUR_PESERTA_REQUEST = "DTS_UMUR_PESERTA_REQUEST";
export const DTS_UMUR_PESERTA_SUCCESS = "DTS_UMUR_PESERTA_SUCCESS";
export const DTS_UMUR_PESERTA_FAIL = "DTS_UMUR_PESERTA_FAIL";

export const DTS_UMUR_PENDAFTAR_REQUEST = "DTS_UMUR_PENDAFTAR_REQUEST";
export const DTS_UMUR_PENDAFTAR_SUCCESS = "DTS_UMUR_PENDAFTAR_SUCCESS";
export const DTS_UMUR_PENDAFTAR_FAIL = "DTS_UMUR_PENDAFTAR_FAIL";

// JENIS KELAMIN PENDAFTAR || PESERTA
export const DTS_JENIS_KELAMIN_PESERTA_REQUEST =
  "DTS_JENIS_KELAMIN_PESERTA_REQUEST";
export const DTS_JENIS_KELAMIN_PESERTA_SUCCESS =
  "DTS_JENIS_KELAMIN_PESERTA_SUCCESS";
export const DTS_JENIS_KELAMIN_PESERTA_FAIL = "DTS_JENIS_KELAMIN_PESERTA_FAIL";

export const DTS_JENIS_KELAMIN_PENDAFTAR_REQUEST =
  "DTS_JENIS_KELAMIN_PENDAFTAR_REQUEST";
export const DTS_JENIS_KELAMIN_PENDAFTAR_SUCCESS =
  "DTS_JENIS_KELAMIN_PENDAFTAR_SUCCESS";
export const DTS_JENIS_KELAMIN_PENDAFTAR_FAIL =
  "DTS_JENIS_KELAMIN_PENDAFTAR_FAIL";

// PENDIDIKAN PENDAFTAR || PESERTA
export const DTS_PENDIDIKAN_PENDAFTAR_REQUEST =
  "DTS_PENDIDIKAN_PENDAFTAR_REQUEST";
export const DTS_PENDIDIKAN_PENDAFTAR_SUCCESS =
  "DTS_PENDIDIKAN_PENDAFTAR_SUCCESS";
export const DTS_PENDIDIKAN_PENDAFTAR_FAIL = "DTS_PENDIDIKAN_PENDAFTAR_FAIL";

export const DTS_PENDIDIKAN_PESERTA_REQUEST = "DTS_PENDIDIKAN_PESERTA_REQUEST";
export const DTS_PENDIDIKAN_PESERTA_SUCCESS = "DTS_PENDIDIKAN_PESERTA_SUCCESS";
export const DTS_PENDIDIKAN_PESERTA_FAIL = "DTS_PENDIDIKAN_PESERTA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
