// TOTAL DATA PENDAFTAR
export const DTS_TOTAL_PENDAFTAR_REQUEST = "DTS_TOTAL_PENDAFTAR_REQUEST";
export const DTS_TOTAL_PENDAFTAR_SUCCESS = "DTS_TOTAL_PENDAFTAR_SUCCESS";
export const DTS_TOTAL_PENDAFTAR_FAIL = "DTS_TOTAL_PENDAFTAR_FAIL";

// TOTAL PENGGUNA
export const DTS_TOTAL_PENGGUNA_REQUEST = "DTS_TOTAL_PENGGUNA_REQUEST";
export const DTS_TOTAL_PENGGUNA_SUCCESS = "DTS_TOTAL_PENGGUNA_SUCCESS";
export const DTS_TOTAL_PENGGUNA_FAIL = "DTS_TOTAL_PENGGUNA_FAIL";

// STATISTIK PESERTA
export const DTS_STATISTIK_AKADEMI_PESERTA_REQUEST =
  "DTS_STATISTIK_AKADEMI_PESERTA_REQUEST";
export const DTS_STATISTIK_AKADEMI_PESERTA_SUCCESS =
  "DTS_STATISTIK_AKADEMI_PESERTA_SUCCESS";
export const DTS_STATISTIK_AKADEMI_PESERTA_FAIL =
  "DTS_STATISTIK_AKADEMI_PESERTA_FAIL";

export const DTS_STATISTIK_AKADEMI_PENDAFTAR_REQUEST =
  "DTS_STATISTIK_AKADEMI_PENDAFTAR_REQUEST";
export const DTS_STATISTIK_AKADEMI_PENDAFTAR_SUCCESS =
  "DTS_STATISTIK_AKADEMI_PENDAFTAR_SUCCESS";
export const DTS_STATISTIK_AKADEMI_PENDAFTAR_FAIL =
  "DTS_STATISTIK_AKADEMI_PESERTA_FAIL";

//   STATISTIK MITRA
export const DTS_STATISTIK_MITRA_PENDAFTAR_REQUEST =
  "DTS_STATISTIK_MITRA_PENDAFTAR_REQUEST";
export const DTS_STATISTIK_MITRA_PENDAFTAR_SUCCESS =
  "DTS_STATISTIK_MITRA_PENDAFTAR_SUCCESS";
export const DTS_STATISTIK_MITRA_PENDAFTAR_FAIL =
  "DTS_STATISTIK_MITRA_PESERTA_FAIL";

export const DTS_STATISTIK_MITRA_PESERTA_REQUEST =
  "DTS_STATISTIK_MITRA_PESERTA_REQUEST";
export const DTS_STATISTIK_MITRA_PESERTA_SUCCESS =
  "DTS_STATISTIK_MITRA_PESERTA_SUCCESS";
export const DTS_STATISTIK_MITRA_PESERTA_FAIL =
  "DTS_STATISTIK_MITRA_PESERTA_FAIL";

//   TABLE PENDAFTARAN DIBUKA
export const DTS_LIST_PENDAFTARAN_REQUEST = "DTS_LIST_PENDAFTARAN_REQUEST";
export const DTS_LIST_PENDAFTARAN_SUCCESS = "DTS_LIST_PENDAFTARAN_SUCCESS";
export const DTS_LIST_PENDAFTARAN_FAIL = "DTS_LIST_PENDAFTARAN_FAIL";

// PENYEBARAN PESERTA WILAYAH
export const DTS_LIST_PESERTA_WILAYAH_REQUEST =
  "DTS_LIST_PESERTA_WILAYAH_REQUEST";
export const DTS_LIST_PESERTA_WILAYAH_SUCCESS =
  "DTS_LIST_PESERTA_WILAYAH_SUCCESS";
export const DTS_LIST_PESERTA_WILAYAH_FAIL = "DTS_LIST_PESERTA_WILAYAH_FAIL";

// PROVINSI PENDAFTAR || PESERTA
export const DTS_PROVINSI_PENDAFTAR_REQUEST = "DTS_PROVINSI_PENDAFTAR_REQUEST";
export const DTS_PROVINSI_PENDAFTAR_SUCCESS = "DTS_PROVINSI_PENDAFTAR_SUCCESS";
export const DTS_PROVINSI_PENDAFTAR_FAIL = "DTS_PROVINSI_PENDAFTAR_FAIL";

export const DTS_PROVINSI_PESERTA_REQUEST = "DTS_PROVINSI_PESERTA_REQUEST";
export const DTS_PROVINSI_PESERTA_SUCCESS = "DTS_PROVINSI_PESERTA_SUCCESS";
export const DTS_PROVINSI_PESERTA_FAIL = "DTS_PROVINSI_PESERTA_FAIL";

// DATA PRIBADI UMUR | JENIS KELAMIN | PEKERJAAN
export const DTS_PRIBADI_PESERTA_REQUEST = "DTS_PRIBADI_PESERTA_REQUEST";
export const DTS_PRIBADI_PESERTA_SUCCESS = "DTS_PRIBADI_PESERTA_SUCCESS";
export const DTS_PRIBADI_PESERTA_FAIL = "DTS_PRIBADI_PESERTA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
