// SIMONAS COMPANY
export const SIMONAS_COMPANY_TOTAL_REQUEST = "SIMONAS_COMPANY_TOTAL_REQUEST";
export const SIMONAS_COMPANY_TOTAL_SUCCESS = "SIMONAS_COMPANY_TOTAL_SUCCESS";
export const SIMONAS_COMPANY_TOTAL_FAIL = "SIMONAS_COMPANY_TOTAL_FAIL";

export const SIMONAS_PROJECT_TOTAL_REQUEST = "SIMONAS_PROJECT_TOTAL_REQUEST";
export const SIMONAS_PROJECT_TOTAL_SUCCESS = "SIMONAS_PROJECT_TOTAL_SUCCESS";
export const SIMONAS_PROJECT_TOTAL_FAIL = "SIMONAS_PROJECT_TOTAL_FAIL";

export const SIMONAS_COMPANY_AMOUNT_REQUEST = "SIMONAS_COMPANY_AMOUNT_REQUEST";
export const SIMONAS_COMPANY_AMOUNT_SUCCESS = "SIMONAS_COMPANY_AMOUNT_SUCCESS";
export const SIMONAS_COMPANY_AMOUNT_FAIL = "SIMONAS_COMPANY_AMOUNT_FAIL";

export const SIMONAS_PROJECT_AMOUNT_REQUEST = "SIMONAS_PROJECT_AMOUNT_REQUEST";
export const SIMONAS_PROJECT_AMOUNT_SUCCESS = "SIMONAS_PROJECT_AMOUNT_SUCCESS";
export const SIMONAS_PROJECT_AMOUNT_FAIL = "SIMONAS_PROJECT_AMOUNT_FAIL";

// SIMONAS APPLIER
// TOTAL PELAMAR
export const SIMONAS_APPLIER_TOTAL_REQUEST = "SIMONAS_APPLIER_TOTAL_REQUEST";
export const SIMONAS_APPLIER_TOTAL_SUCCESS = "SIMONAS_APPLIER_TOTAL_SUCCESS";
export const SIMONAS_APPLIER_TOTAL_FAIL = "SIMONAS_APPLIER_TOTAL_FAIL";

export const SIMONAS_APPLIER_TOTAL_ACTIVE_REQUEST =
  "SIMONAS_APPLIER_TOTAL_ACTIVE_REQUEST";
export const SIMONAS_APPLIER_TOTAL_ACTIVE_SUCCESS =
  "SIMONAS_APPLIER_TOTAL_ACTIVE_SUCCESS";
export const SIMONAS_APPLIER_TOTAL_ACTIVE_FAIL =
  "SIMONAS_APPLIER_TOTAL_ACTIVE_FAIL";

// REGION PELAMAR
export const SIMONAS_REGION_APPLIER_REQUEST = "SIMONAS_REGION_APPLIER_REQUEST";
export const SIMONAS_REGION_APPLIER_SUCCESS = "SIMONAS_REGION_APPLIER_SUCCESS";
export const SIMONAS_REGION_APPLIER_FAIL = "SIMONAS_REGION_APPLIER_FAIL";

export const SIMONAS_FILTER_YEAR_REQUEST = "SIMONAS_FILTER_YEAR_REQUEST";
export const SIMONAS_FILTER_YEAR_SUCCESS = "SIMONAS_FILTER_YEAR_SUCCESS";
export const SIMONAS_FILTER_YEAR_FAIL = "SIMONAS_FILTER_YEAR_FAIL";

export const SIMONAS_FILTER_STATUS_REQUEST = "SIMONAS_FILTER_STATUS_REQUEST";
export const SIMONAS_FILTER_STATUS_SUCCESS = "SIMONAS_FILTER_STATUS_SUCCESS";
export const SIMONAS_FILTER_STATUS_FAIL = "SIMONAS_FILTER_STATUS_FAIL";

// PROVINSI APPLIER SIMONAS
export const SIMONAS_PROVINSI_APPLIER_REQUEST =
  "SIMONAS_PROVINSI_APPLIER_REQUEST";
export const SIMONAS_PROVINSI_APPLIER_SUCCESS =
  "SIMONAS_PROVINSI_APPLIER_SUCCESS";
export const SIMONAS_PROVINSI_APPLIER_FAIL = "SIMONAS_PROVINSI_APPLIER_FAIL";

export const SIMONAS_PROVINSI_APPLIER_REQUITED_REQUEST =
  "SIMONAS_PROVINSI_APPLIER_REQUITED_REQUEST";
export const SIMONAS_PROVINSI_APPLIER_REQUITED_SUCCESS =
  "SIMONAS_PROVINSI_APPLIER_REQUITED_SUCCESS";
export const SIMONAS_PROVINSI_APPLIER_REQUITED_FAIL =
  "SIMONAS_PROVINSI_APPLIER_REQUITED_FAIL";

// JUMLAH PELAMAR
export const SIMONAS_APPLIER_AMOUNT_JOB_REQUEST =
  "SIMONAS_APPLIER_AMOUNT_JOB_REQUEST";
export const SIMONAS_APPLIER_AMOUNT_JOB_SUCCESS =
  "SIMONAS_APPLIER_AMOUNT_JOB_SUCCESS";
export const SIMONAS_APPLIER_AMOUNT_JOB_FAIL =
  "SIMONAS_APPLIER_AMOUNT_JOB_FAIL";

export const SIMONAS_APPLIER_AMOUNT_PROJECT_REQUEST =
  "SIMONAS_APPLIER_AMOUNT_PROJECT_REQUEST";
export const SIMONAS_APPLIER_AMOUNT_PROJECT_SUCCESS =
  "SIMONAS_APPLIER_AMOUNT_PROJECT_SUCCESS";
export const SIMONAS_APPLIER_AMOUNT_PROJECT_FAIL =
  "SIMONAS_APPLIER_AMOUNT_PROJECT_FAIL";

// UMUR PELAMAR
export const SIMONAS_APPLIER_AGE_REQUEST = "SIMONAS_APPLIER_AGE_REQUEST";
export const SIMONAS_APPLIER_AGE_SUCCESS = "SIMONAS_APPLIER_AGE_SUCCESS";
export const SIMONAS_APPLIER_AGE_FAIL = "SIMONAS_APPLIER_AGE_FAIL";

// JENIS KELAMIN PELAMAR
export const SIMONAS_APPLIER_GENDER_REQUEST = "SIMONAS_APPLIER_GENDER_REQUEST";
export const SIMONAS_APPLIER_GENDER_SUCCESS = "SIMONAS_APPLIER_GENDER_SUCCESS";
export const SIMONAS_APPLIER_GENDER_FAIL = "SIMONAS_APPLIER_GENDER_FAIL";

// PENDIDIKAN PELAMAR
export const SIMONAS_APPLIER_EDUCATION_JOB_REQUEST =
  "SIMONAS_APPLIER_EDUCATION_JOB_REQUEST";
export const SIMONAS_APPLIER_EDUCATION_JOB_SUCCESS =
  "SIMONAS_APPLIER_EDUCATION_JOB_SUCCESS";
export const SIMONAS_APPLIER_EDUCATION_JOB_FAIL =
  "SIMONAS_APPLIER_EDUCATION_JOB_FAIL";

export const SIMONAS_APPLIER_EDUCATION_PROJECT_REQUEST =
  "SIMONAS_APPLIER_EDUCATION_PROJECT_REQUEST";
export const SIMONAS_APPLIER_EDUCATION_PROJECT_SUCCESS =
  "SIMONAS_APPLIER_EDUCATION_PROJECT_SUCCESS";
export const SIMONAS_APPLIER_EDUCATION_PROJECT_FAIL =
  "SIMONAS_APPLIER_EDUCATION_PROJECT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
