export const OPTION_ACADEMY_REQUEST = "OPTION_ACADEMY_REQUEST";
export const OPTION_ACADEMY_SUCCESS = "OPTION_ACADEMY_SUCCESS";
export const OPTION_ACADEMY_FAIL = "OPTION_ACADEMY_FAIL";

export const OPTION_THEME_REQUEST = "OPTION_THEME_REQUEST";
export const OPTION_THEME_SUCCESS = "OPTION_THEME_SUCCESS";
export const OPTION_THEME_FAIL = "OPTION_THEME_FAIL";

export const OPTION_TRAINING_REQUEST = "OPTION_TRAINING_REQUEST";
export const OPTION_TRAINING_SUCCESS = "OPTION_TRAINING_SUCCESS";
export const OPTION_TRAINING_FAIL = "OPTION_TRAINING_FAIL";
