export const SERTIFIKAT_REQUEST = "SERTIFIKAT_REQUEST";
export const SERTIFIKAT_SUCCESS = "SERTIFIKAT_SUCCESS";
export const SERTIFIKAT_FAIL = "SERTIFIKAT_FAIL";

export const SET_KEYWORD_VALUE = "SET_KEYWORD_VALUE";
export const SET_ACADEMY_VALUE = "SET_ACADEMY_VALUE";
export const SET_THEME_VALUE = "SET_THEME_VALUE";
export const SET_PAGE_VALUE = "SET_PAGE_VALUE";
export const SET_LIMIT_VALUE = "SET_LIMIT_VALUE";

export const RESET_VALUE_FILTER = "RESET_VALUE_FILTER";

export const NEW_SERTIFIKAT_REQUEST = "NEW_SERTIFIKAT_REQUEST";
export const NEW_SERTIFIKAT_SUCCESS = "NEW_SERTIFIKAT_SUCCESS";
export const NEW_SERTIFIKAT_RESET = "NEW_SERTIFIKAT_RESET";
export const NEW_SERTIFIKAT_FAIL = "NEW_SERTIFIKAT_FAIL";

export const DETAIL_SERTIFIKAT_REQUEST = "DETAIL_SERTIFIKAT_REQUEST";
export const DETAIL_SERTIFIKAT_SUCCESS = "DETAIL_SERTIFIKAT_SUCCESS";
export const DETAIL_SERTIFIKAT_FAIL = "DETAIL_SERTIFIKAT_FAIL";

export const UPDATE_SERTIFIKAT_REQUEST = "UPDATE_SERTIFIKAT_REQUEST";
export const UPDATE_SERTIFIKAT_SUCCESS = "UPDATE_SERTIFIKAT_SUCCESS";
export const UPDATE_SERTIFIKAT_RESET = "UPDATE_SERTIFIKAT_RESET";
export const UPDATE_SERTIFIKAT_FAIL = "UPDATE_SERTIFIKAT_FAIL";

export const DELETE_SERTIFIKAT_REQUEST = "DELETE_SERTIFIKAT_REQUEST";
export const DELETE_SERTIFIKAT_SUCCESS = "DELETE_SERTIFIKAT_SUCCESS";
export const DELETE_SERTIFIKAT_RESET = "DELETE_SERTIFIKAT_RESET";
export const DELETE_SERTIFIKAT_FAIL = "DELETE_SERTIFIKAT_FAIL";

export const SINGLE_SERTIFIKAT_REQUEST = "SINGLE_SERTIFIKAT_REQUEST";
export const SINGLE_SERTIFIKAT_SUCCESS = "SINGLE_SERTIFIKAT_SUCCESS";
export const SINGLE_SERTIFIKAT_FAIL = "SINGLE_SERTIFIKAT_FAIL";

export const PUBLISHED_SERTIFIKAT_REQUEST = "PUBLISHED_SERTIFIKAT_REQUEST";
export const PUBLISHED_SERTIFIKAT_SUCCESS = "PUBLISHED_SERTIFIKAT_SUCCESS";
export const PUBLISHED_SERTIFIKAT_FAIL = "PUBLISHED_SERTIFIKAT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const OPTIONS_ACADEMY_REQUEST = "OPTIONS_ACADEMY_REQUEST";
export const OPTIONS_ACADEMY_SUCCESS = "OPTIONS_ACADEMY_SUCCESS";
export const OPTIONS_ACADEMY_FAIL = "OPTIONS_ACADEMY_FAIL";

export const OPTIONS_THEME_REQUEST = "OPTIONS_THEME_REQUEST";
export const OPTIONS_THEME_SUCCESS = "OPTIONS_THEME_SUCCESS";
export const OPTIONS_THEME_FAIL = "OPTIONS_THEME_FAIL";
