export const LIST_PESERTA_REQUEST = "LIST_PESERTA_REQUEST";
export const LIST_PESERTA_SUCCESS = "LIST_PESERTA_SUCCESS";
export const LIST_PESERTA_FAIL = "LIST_PESERTA_FAIL";

export const NEW_LIST_PESERTA_REQUEST = "NEW_LIST_PESERTA_REQUEST";
export const NEW_LIST_PESERTA_SUCCESS = "NEW_LIST_PESERTA_SUCCESS";
export const NEW_LIST_PESERTA_RESET = "NEW_LIST_PESERTA_RESET";
export const NEW_LIST_PESERTA_FAIL = "NEW_LIST_PESERTA_FAIL";

export const DETAIL_LIST_PESERTA_REQUEST = "DETAIL_LIST_PESERTA_REQUEST";
export const DETAIL_LIST_PESERTA_SUCCESS = "DETAIL_LIST_PESERTA_SUCCESS";
export const DETAIL_LIST_PESERTA_FAIL = "DETAIL_LIST_PESERTA_FAIL";

export const UPDATE_LIST_PESERTA_REQUEST = "UPDATE_LIST_PESERTA_REQUEST";
export const UPDATE_LIST_PESERTA_SUCCESS = "UPDATE_LIST_PESERTA_SUCCESS";
export const UPDATE_LIST_PESERTA_RESET = "UPDATE_LIST_PESERTA_RESET";
export const UPDATE_LIST_PESERTA_FAIL = "UPDATE_LIST_PESERTA_FAIL";

export const DELETE_LIST_PESERTA_REQUEST = "DELETE_LIST_PESERTA_REQUEST";
export const DELETE_LIST_PESERTA_SUCCESS = "DELETE_LIST_PESERTA_SUCCESS";
export const DELETE_LIST_PESERTA_RESET = "DELETE_LIST_PESERTA_RESET";
export const DELETE_LIST_PESERTA_FAIL = "DELETE_LIST_PESERTA_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
