export const ARTIKEL_PESERTA_REQUEST = 'ARTIKEL_PESERTA_REQUEST'
export const ARTIKEL_PESERTA_SUCCESS = 'ARTIKEL_PESERTA_SUCCESS'
export const ARTIKEL_PESERTA_FAIL = 'ARTIKEL_PESERTA_FAIL'

export const NEW_ARTIKEL_PESERTA_REQUEST = 'NEW_ARTIKEL_PESERTA_REQUEST'
export const NEW_ARTIKEL_PESERTA_SUCCESS = 'NEW_ARTIKEL_PESERTA_SUCCESS'
export const NEW_ARTIKEL_PESERTA_RESET = 'NEW_ARTIKEL_PESERTA_RESET'
export const NEW_ARTIKEL_PESERTA_FAIL = 'NEW_ARTIKEL_PESERTA_FAIL'

export const DETAIL_ARTIKEL_PESERTA_REQUEST = 'DETAIL_ARTIKEL_PESERTA_REQUEST'
export const DETAIL_ARTIKEL_PESERTA_SUCCESS = 'DETAIL_ARTIKEL_PESERTA_SUCCESS'
export const DETAIL_ARTIKEL_PESERTA_FAIL = 'DETAIL_ARTIKEL_PESERTA_FAIL'

export const UPDATE_ARTIKEL_PESERTA_REQUEST = 'UPDATE_ARTIKEL_PESERTA_REQUEST'
export const UPDATE_ARTIKEL_PESERTA_SUCCESS = 'UPDATE_ARTIKEL_PESERTA_SUCCESS'
export const UPDATE_ARTIKEL_PESERTA_RESET = 'UPDATE_ARTIKEL_PESERTA_RESET'
export const UPDATE_ARTIKEL_PESERTA_FAIL = 'UPDATE_ARTIKEL_PESERTA_FAIL'

export const DELETE_ARTIKEL_PESERTA_REQUEST = 'DELETE_ARTIKEL_PESERTA_REQUEST'
export const DELETE_ARTIKEL_PESERTA_SUCCESS = 'DELETE_ARTIKEL_PESERTA_SUCCESS'
export const DELETE_ARTIKEL_PESERTA_RESET = 'DELETE_ARTIKEL_PESERTA_RESET'
export const DELETE_ARTIKEL_PESERTA_FAIL = 'DELETE_ARTIKEL_PESERTA_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'