export const BERITA_REQUEST = 'BERITA_REQUEST'
export const BERITA_SUCCESS = 'BERITA_SUCCESS'
export const BERITA_FAIL = 'BERITA_FAIL'

export const NEW_BERITA_REQUEST = 'NEW_BERITA_REQUEST'
export const NEW_BERITA_SUCCESS = 'NEW_BERITA_SUCCESS'
export const NEW_BERITA_RESET = 'NEW_BERITA_RESET'
export const NEW_BERITA_FAIL = 'NEW_BERITA_FAIL'

export const DETAIL_BERITA_REQUEST = 'DETAIL_BERITA_REQUEST'
export const DETAIL_BERITA_SUCCESS = 'DETAIL_BERITA_SUCCESS'
export const DETAIL_BERITA_FAIL = 'DETAIL_BERITA_FAIL'

export const UPDATE_BERITA_REQUEST = 'UPDATE_BERITA_REQUEST'
export const UPDATE_BERITA_SUCCESS = 'UPDATE_BERITA_SUCCESS'
export const UPDATE_BERITA_RESET = 'UPDATE_BERITA_RESET'
export const UPDATE_BERITA_FAIL = 'UPDATE_BERITA_FAIL'

export const DELETE_BERITA_REQUEST = 'DELETE_BERITA_REQUEST'
export const DELETE_BERITA_SUCCESS = 'DELETE_BERITA_SUCCESS'
export const DELETE_BERITA_RESET = 'DELETE_BERITA_RESET'
export const DELETE_BERITA_FAIL = 'DELETE_BERITA_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'