export const DASHBOARD_PUBLIKASI_REQUEST = 'DASHBOARD_PUBLIKASI_REQUEST'
export const DASHBOARD_PUBLIKASI_SUCCESS = 'DASHBOARD_PUBLIKASI_SUCCESS'
export const DASHBOARD_PUBLIKASI_FAIL = 'DASHBOARD_PUBLIKASI_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'