export const DASHBOARD_PUBLIKASI_REQUEST = 'DASHBOARD_PUBLIKASI_REQUEST'
export const DASHBOARD_PUBLIKASI_SUCCESS = 'DASHBOARD_PUBLIKASI_SUCCESS'
export const DASHBOARD_PUBLIKASI_FAIL = 'DASHBOARD_PUBLIKASI_FAIL'

export const ROLE_ADMIN_REQUEST = 'ROLE_ADMIN_REQUEST'
export const ROLE_ADMIN_SUCCESS = 'ROLE_ADMIN_SUCCESS'
export const ROLE_ADMIN_FAIL = 'ROLE_ADMIN_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'