export const FAQ_REQUEST = 'FAQ_REQUEST'
export const FAQ_SUCCESS = 'FAQ_SUCCESS'
export const FAQ_FAIL = 'FAQ_FAIL'

export const PAGINATION_FAQ_REQUEST = 'FAQ_REQUEST'
export const PAGINATION_FAQ_SUCCESS = 'FAQ_SUCCESS'
export const PAGINATION_FAQ_FAIL = 'FAQ_FAIL'

export const NEW_FAQ_REQUEST = 'NEW_FAQ_REQUEST'
export const NEW_FAQ_SUCCESS = 'NEW_FAQ_SUCCESS'
export const NEW_FAQ_RESET = 'NEW_FAQ_RESET'
export const NEW_FAQ_FAIL = 'NEW_FAQ_FAIL'

export const DETAIL_FAQ_REQUEST = 'DETAIL_FAQ_REQUEST'
export const DETAIL_FAQ_SUCCESS = 'DETAIL_FAQ_SUCCESS'
export const DETAIL_FAQ_FAIL = 'DETAIL_FAQ_FAIL'

export const UPDATE_FAQ_REQUEST = 'UPDATE_FAQ_REQUEST'
export const UPDATE_FAQ_SUCCESS = 'UPDATE_FAQ_SUCCESS'
export const UPDATE_FAQ_RESET = 'UPDATE_FAQ_RESET'
export const UPDATE_FAQ_FAIL = 'UPDATE_FAQ_FAIL'

export const DELETE_FAQ_REQUEST = 'DELETE_FAQ_REQUEST'
export const DELETE_FAQ_SUCCESS = 'DELETE_FAQ_SUCCESS'
export const DELETE_FAQ_RESET = 'DELETE_FAQ_RESET'
export const DELETE_FAQ_FAIL = 'DELETE_FAQ_FAIL'

export const UPDATE_PIN_FAQ_REQUEST = 'UPDATE_PIN_FAQ_REQUEST'
export const UPDATE_PIN_FAQ_SUCCESS = 'UPDATE_PIN_FAQ_SUCCESS'
export const UPDATE_PIN_FAQ_RESET = 'UPDATE_PIN_FAQ_RESET'
export const UPDATE_PIN_FAQ_FAIL = 'UPDATE_PIN_FAQ_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'