export const GALERI_REQUEST = 'GALERI_REQUEST'
export const GALERI_SUCCESS = 'GALERI_SUCCESS'
export const GALERI_FAIL = 'GALERI_FAIL'

export const NEW_GALERI_REQUEST = 'NEW_GALERI_REQUEST'
export const NEW_GALERI_SUCCESS = 'NEW_GALERI_SUCCESS'
export const NEW_GALERI_RESET = 'NEW_GALERI_RESET'
export const NEW_GALERI_FAIL = 'NEW_GALERI_FAIL'

export const DETAIL_GALERI_REQUEST = 'DETAIL_GALERI_REQUEST'
export const DETAIL_GALERI_SUCCESS = 'DETAIL_GALERI_SUCCESS'
export const DETAIL_GALERI_FAIL = 'DETAIL_GALERI_FAIL'

export const UPDATE_GALERI_REQUEST = 'UPDATE_GALERI_REQUEST'
export const UPDATE_GALERI_SUCCESS = 'UPDATE_GALERI_SUCCESS'
export const UPDATE_GALERI_RESET = 'UPDATE_GALERI_RESET'
export const UPDATE_GALERI_FAIL = 'UPDATE_GALERI_FAIL'

export const DELETE_GALERI_REQUEST = 'DELETE_GALERI_REQUEST'
export const DELETE_GALERI_SUCCESS = 'DELETE_GALERI_SUCCESS'
export const DELETE_GALERI_RESET = 'DELETE_GALERI_RESET'
export const DELETE_GALERI_FAIL = 'DELETE_GALERI_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'