export const IMAGETRON_REQUEST = 'IMAGETRON_REQUEST'
export const IMAGETRON_SUCCESS = 'IMAGETRON_SUCCESS'
export const IMAGETRON_FAIL = 'IMAGETRON_FAIL'

export const NEW_IMAGETRON_REQUEST = 'NEW_IMAGETRON_REQUEST'
export const NEW_IMAGETRON_SUCCESS = 'NEW_IMAGETRON_SUCCESS'
export const NEW_IMAGETRON_RESET = 'NEW_IMAGETRON_RESET'
export const NEW_IMAGETRON_FAIL = 'NEW_IMAGETRON_FAIL'

export const DETAIL_IMAGETRON_REQUEST = 'DETAIL_IMAGETRON_REQUEST'
export const DETAIL_IMAGETRON_SUCCESS = 'DETAIL_IMAGETRON_SUCCESS'
export const DETAIL_IMAGETRON_FAIL = 'DETAIL_IMAGETRON_FAIL'

export const UPDATE_IMAGETRON_REQUEST = 'UPDATE_IMAGETRON_REQUEST'
export const UPDATE_IMAGETRON_SUCCESS = 'UPDATE_IMAGETRON_SUCCESS'
export const UPDATE_IMAGETRON_RESET = 'UPDATE_IMAGETRON_RESET'
export const UPDATE_IMAGETRON_FAIL = 'UPDATE_IMAGETRON_FAIL'

export const DELETE_IMAGETRON_REQUEST = 'DELETE_IMAGETRON_REQUEST'
export const DELETE_IMAGETRON_SUCCESS = 'DELETE_IMAGETRON_SUCCESS'
export const DELETE_IMAGETRON_RESET = 'DELETE_IMAGETRON_RESET'
export const DELETE_IMAGETRON_FAIL = 'DELETE_IMAGETRON_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'