export const KATEGORI_REQUEST = 'KATEGORI_REQUEST'
export const KATEGORI_SUCCESS = 'KATEGORI_SUCCESS'
export const KATEGORI_FAIL = 'KATEGORI_FAIL'

export const PAGINATION_KATEGORI_REQUEST = 'PAGINATION_KATEGORI_REQUEST'
export const PAGINATION_KATEGORI_SUCCESS = 'PAGINATION_KATEGORI_SUCCESS'
export const PAGINATION_KATEGORI_FAIL = 'PAGINATION_KATEGORI_FAIL'

export const NEW_KATEGORI_REQUEST = 'NEW_KATEGORI_REQUEST'
export const NEW_KATEGORI_SUCCESS = 'NEW_KATEGORI_SUCCESS'
export const NEW_KATEGORI_RESET = 'NEW_KATEGORI_RESET'
export const NEW_KATEGORI_FAIL = 'NEW_KATEGORI_FAIL'

export const DETAIL_KATEGORI_REQUEST = 'DETAIL_KATEGORI_REQUEST'
export const DETAIL_KATEGORI_SUCCESS = 'DETAIL_KATEGORI_SUCCESS'
export const DETAIL_KATEGORI_FAIL = 'DETAIL_KATEGORI_FAIL'

export const UPDATE_KATEGORI_REQUEST = 'UPDATE_KATEGORI_REQUEST'
export const UPDATE_KATEGORI_SUCCESS = 'UPDATE_KATEGORI_SUCCESS'
export const UPDATE_KATEGORI_RESET = 'UPDATE_KATEGORI_RESET'
export const UPDATE_KATEGORI_FAIL = 'UPDATE_KATEGORI_FAIL'

export const DELETE_KATEGORI_REQUEST = 'DELETE_KATEGORI_REQUEST'
export const DELETE_KATEGORI_SUCCESS = 'DELETE_KATEGORI_SUCCESS'
export const DELETE_KATEGORI_RESET = 'DELETE_KATEGORI_RESET'
export const DELETE_KATEGORI_FAIL = 'DELETE_KATEGORI_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'