export const ROLE_PERMISSION_REQUEST = 'ROLE_PERMISSION_REQUEST'
export const ROLE_PERMISSION_SUCCESS = 'ROLE_PERMISSION_SUCCESS'
export const ROLE_PERMISSION_FAIL = 'ROLE_PERMISSION_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'