export const SETTING_REQUEST = 'SETTING_REQUEST'
export const SETTING_SUCCESS = 'SETTING_SUCCESS'
export const SETTING_FAIL = 'SETTING_FAIL'

export const UPDATE_SETTING_REQUEST = 'UPDATE_SETTING_REQUEST'
export const UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS'
export const UPDATE_SETTING_RESET = 'UPDATE_SETTING_RESET'
export const UPDATE_SETTING_FAIL = 'UPDATE_SETTING_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'