export const SETTING_REQUEST = 'SETTING_REQUEST'
export const SETTING_SUCCESS = 'SETTING_SUCCESS'
export const SETTING_FAIL = 'SETTING_FAIL'

export const UPDATE_SETTING_REQUEST = 'UPDATE_SETTING_REQUEST'

export const UPDATE_SETTING_IMAGE_SUCCESS = 'UPDATE_SETTING_IMAGE_SUCCESS'
export const UPDATE_SETTING_IMAGETRON_SUCCESS = 'UPDATE_SETTING_IMAGETRON_SUCCESS'
export const UPDATE_SETTING_SLIDER_SUCCESS = 'UPDATE_SETTING_SLIDER_SUCCESS'
export const UPDATE_SETTING_FAQ_SUCCESS = 'UPDATE_SETTING_FAQ_SUCCESS'

export const UPDATE_SETTING_IMAGE_FAIL = 'UPDATE_SETTING_IMAGE_FAIL'
export const UPDATE_SETTING_IMAGETRON_FAIL = 'UPDATE_SETTING_IMAGETRON_FAIL'
export const UPDATE_SETTING_SLIDER_FAIL = 'UPDATE_SETTING_SLIDER_FAIL'
export const UPDATE_SETTING_FAQ_FAIL = 'UPDATE_SETTING_FAQ_FAIL'

export const UPDATE_SETTING_RESET = 'UPDATE_SETTING_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'