export const VIDEO_REQUEST = 'VIDEO_REQUEST'
export const VIDEO_SUCCESS = 'VIDEO_SUCCESS'
export const VIDEO_FAIL = 'VIDEO_FAIL'

export const NEW_VIDEO_REQUEST = 'NEW_VIDEO_REQUEST'
export const NEW_VIDEO_SUCCESS = 'NEW_VIDEO_SUCCESS'
export const NEW_VIDEO_RESET = 'NEW_VIDEO_RESET'
export const NEW_VIDEO_FAIL = 'NEW_VIDEO_FAIL'

export const DETAIL_VIDEO_REQUEST = 'DETAIL_VIDEO_REQUEST'
export const DETAIL_VIDEO_SUCCESS = 'DETAIL_VIDEO_SUCCESS'
export const DETAIL_VIDEO_FAIL = 'DETAIL_VIDEO_FAIL'

export const UPDATE_VIDEO_REQUEST = 'UPDATE_VIDEO_REQUEST'
export const UPDATE_VIDEO_SUCCESS = 'UPDATE_VIDEO_SUCCESS'
export const UPDATE_VIDEO_RESET = 'UPDATE_VIDEO_RESET'
export const UPDATE_VIDEO_FAIL = 'UPDATE_VIDEO_FAIL'

export const DELETE_VIDEO_REQUEST = 'DELETE_VIDEO_REQUEST'
export const DELETE_VIDEO_SUCCESS = 'DELETE_VIDEO_SUCCESS'
export const DELETE_VIDEO_RESET = 'DELETE_VIDEO_RESET'
export const DELETE_VIDEO_FAIL = 'DELETE_VIDEO_FAIL'

export const PLAY_VIDEO_REQUEST = 'PLAY_VIDEO_REQUEST'
export const PLAY_VIDEO_SUCCESS = 'PLAY_VIDEO_SUCCESS'
export const PLAY_VIDEO_FAIL = 'PLAY_VIDEO_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const TAG_REQUEST = 'TAG_REQUEST'
export const TAG_SUCCESS = 'TAG_SUCCESS'
export const TAG_FAIL = 'TAG_FAIL'

export const PLAY_REQUEST = 'PLAY_REQUEST'
export const PLAY_SUCCESS = 'PLAY_SUCCESS'
export const PLAY_FAIL = 'PLAY_FAIL'

export const KATEGORI_VIDEO_CONTENT_REQUEST = 'KATEGORI_VIDEO_CONTENT_REQUEST'
export const KATEGORI_VIDEO_CONTENT_SUCCESS = 'KATEGORI_VIDEO_CONTENT_SUCCESS'
export const KATEGORI_VIDEO_CONTENT_FAIL = 'KATEGORI_VIDEO_CONTENT_FAIL'

export const SET_FILTER_CARD = 'SET_FILTER_CARD'