export const BERANDA_ARTIKEL_REQUEST = 'BERANDA_ARTIKEL_REQUEST'
export const BERANDA_ARTIKEL_SUCCESS = 'BERANDA_ARTIKEL_SUCCESS'
export const BERANDA_ARTIKEL_FAIL = 'BERANDA_ARTIKEL_FAIL'

export const DETAIL_BERANDA_ARTIKEL_REQUEST = 'DETAIL_BERANDA_ARTIKEL_REQUEST'
export const DETAIL_BERANDA_ARTIKEL_SUCCESS = 'DETAIL_BERANDA_ARTIKEL_SUCCESS'
export const DETAIL_BERANDA_ARTIKEL_FAIL = 'DETAIL_BERANDA_ARTIKEL_FAIL'

export const KATEGORI_BERANDA_ARTIKEL_REQUEST = 'KATEGORI_BERANDA_ARTIKEL_REQUEST'
export const KATEGORI_BERANDA_ARTIKEL_SUCCESS = 'KATEGORI_BERANDA_ARTIKEL_SUCCESS'
export const KATEGORI_BERANDA_ARTIKEL_FAIL = 'KATEGORI_BERANDA_ARTIKEL_FAIL'

export const TAG_BERANDA_ARTIKEL_REQUEST = 'TAG_BERANDA_ARTIKEL_REQUEST'
export const TAG_BERANDA_ARTIKEL_SUCCESS = 'TAG_BERANDA_ARTIKEL_SUCCESS'
export const TAG_BERANDA_ARTIKEL_FAIL = 'TAG_BERANDA_ARTIKEL_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'