export const BERANDA_AKADEMI_REQUEST = "BERANDA_AKADEMI_REQUEST";
export const BERANDA_AKADEMI_SUCCESS = "BERANDA_AKADEMI_SUCCESS";
export const BERANDA_AKADEMI_FAIL = "BERANDA_AKADEMI_FAIL";

export const BERANDA_TEMA_REQUEST = "BERANDA_TEMA_REQUEST";
export const BERANDA_TEMA_SUCCESS = "BERANDA_TEMA_SUCCESS";
export const BERANDA_TEMA_FAIL = "BERANDA_TEMA_FAIL";

export const BERANDA_NOTIF_TEMA_REQUEST = "BERANDA_NOTIF_TEMA_REQUEST";
export const BERANDA_NOTIF_TEMA_SUCCESS = "BERANDA_NOTIF_TEMA_SUCCESS";
export const BERANDA_NOTIF_TEMA_RESET = "BERANDA_NOTIF_TEMA_RESET";
export const BERANDA_NOTIF_TEMA_FAIL = "BERANDA_NOTIF_TEMA_FAIL";
export const CLEAR_ERRORS_NOTIF = "CLEAR_ERRORS_NOTIF";

export const BERANDA_KOTA_REQUEST = "BERANDA_KOTA_REQUEST";
export const BERANDA_KOTA_SUCCESS = "BERANDA_KOTA_SUCCESS";
export const BERANDA_KOTA_FAIL = "BERANDA_KOTA_FAIL";

export const BERANDA_PENYELENGGARA_REQUEST = "BERANDA_PENYELENGGARA_REQUEST";
export const BERANDA_PENYELENGGARA_SUCCESS = "BERANDA_PENYELENGGARA_SUCCESS";
export const BERANDA_PENYELENGGARA_FAIL = "BERANDA_PENYELENGGARA_FAIL";

export const BERANDA_PELATIHAN_REQUEST = "BERANDA_PELATIHAN_REQUEST";
export const BERANDA_PELATIHAN_SUCCESS = "BERANDA_PELATIHAN_SUCCESS";
export const BERANDA_PELATIHAN_FAIL = "BERANDA_PELATIHAN_FAIL";

export const BERANDA_PUBLIKASI_REQUEST = "BERANDA_PUBLIKASI_REQUEST";
export const BERANDA_PUBLIKASI_SUCCESS = "BERANDA_PUBLIKASI_SUCCESS";
export const BERANDA_PUBLIKASI_FAIL = "BERANDA_PUBLIKASI_FAIL";

export const BERANDA_FOOTER_REQUEST = "BERANDA_FOOTER_REQUEST";
export const BERANDA_FOOTER_SUCCESS = "BERANDA_FOOTER_SUCCESS";
export const BERANDA_FOOTER_FAIL = "BERANDA_FOOTER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
