export const BERANDA_AKADEMI_REQUEST = 'BERANDA_AKADEMI_REQUEST'
export const BERANDA_AKADEMI_SUCCESS = 'BERANDA_AKADEMI_SUCCESS'
export const BERANDA_AKADEMI_FAIL = 'BERANDA_AKADEMI_FAIL'

export const BERANDA_TEMA_REQUEST = 'BERANDA_TEMA_REQUEST'
export const BERANDA_TEMA_SUCCESS = 'BERANDA_TEMA_SUCCESS'
export const BERANDA_TEMA_FAIL = 'BERANDA_TEMA_FAIL'

export const BERANDA_PELATIHAN_REQUEST = 'BERANDA_PELATIHAN_REQUEST'
export const BERANDA_PELATIHAN_SUCCESS = 'BERANDA_PELATIHAN_SUCCESS'
export const BERANDA_PELATIHAN_FAIL = 'BERANDA_PELATIHAN_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'