export const BERANDA_BERITA_REQUEST = 'BERANDA_BERITA_REQUEST'
export const BERANDA_BERITA_SUCCESS = 'BERANDA_BERITA_SUCCESS'
export const BERANDA_BERITA_FAIL = 'BERANDA_BERITA_FAIL'

export const DETAIL_BERANDA_BERITA_REQUEST = 'DETAIL_BERANDA_BERITA_REQUEST'
export const DETAIL_BERANDA_BERITA_SUCCESS = 'DETAIL_BERANDA_BERITA_SUCCESS'
export const DETAIL_BERANDA_BERITA_FAIL = 'DETAIL_BERANDA_BERITA_FAIL'

export const KATEGORI_BERANDA_BERITA_REQUEST = 'KATEGORI_BERANDA_BERITA_REQUEST'
export const KATEGORI_BERANDA_BERITA_SUCCESS = 'KATEGORI_BERANDA_BERITA_SUCCESS'
export const KATEGORI_BERANDA_BERITA_FAIL = 'KATEGORI_BERANDA_BERITA_FAIL'

export const TAG_BERANDA_BERITA_REQUEST = 'TAG_BERANDA_BERITA_REQUEST'
export const TAG_BERANDA_BERITA_SUCCESS = 'TAG_BERANDA_BERITA_SUCCESS'
export const TAG_BERANDA_BERITA_FAIL = 'TAG_BERANDA_BERITA_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'