export const DETAIL_PELATIHAN_REQUEST = 'DETAIL_PELATIHAN_REQUEST'
export const DETAIL_PELATIHAN_SUCCESS = 'DETAIL_PELATIHAN_SUCCESS'
export const DETAIL_PELATIHAN_FAIL = 'DETAIL_PELATIHAN_FAIL'

export const CEK_REGISTER_PELATIHAN_REQUEST = 'REGISTER_PELATIHAN_REQUEST'
export const CEK_REGISTER_PELATIHAN_SUCCESS = 'REGISTER_PELATIHAN_SUCCESS'
export const CEK_REGISTER_PELATIHAN_FAIL = 'REGISTER_PELATIHAN_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'