export const DETAIL_AKADEMI_REQUEST = 'DETAIL_AKADEMI_REQUEST'
export const DETAIL_AKADEMI_SUCCESS = 'DETAIL_AKADEMI_SUCCESS'
export const DETAIL_AKADEMI_FAIL = 'DETAIL_AKADEMI_FAIL'

export const PELATIHAN_AKADEMI_REQUEST = 'PELATIHAN_AKADEMI_REQUEST'
export const PELATIHAN_AKADEMI_SUCCESS = 'PELATIHAN_AKADEMI_SUCCESS'
export const PELATIHAN_AKADEMI_FAIL = 'PELATIHAN_AKADEMI_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'