export const BERANDA_FAQ_REQUEST = 'BERANDA_FAQ_REQUEST'
export const BERANDA_FAQ_SUCCESS = 'BERANDA_FAQ_SUCCESS'
export const BERANDA_FAQ_FAIL = 'BERANDA_FAQ_FAIL'

export const KATEGORI_BERANDA_FAQ_REQUEST = 'KATEGORI_BERANDA_FAQ_REQUEST'
export const KATEGORI_BERANDA_FAQ_SUCCESS = 'KATEGORI_BERANDA_FAQ_SUCCESS'
export const KATEGORI_BERANDA_FAQ_FAIL = 'KATEGORI_BERANDA_FAQ_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'