export const BERANDA_GALERI_REQUEST = 'BERANDA_GALERI_REQUEST'
export const BERANDA_GALERI_SUCCESS = 'BERANDA_GALERI_SUCCESS'
export const BERANDA_GALERI_FAIL = 'BERANDA_GALERI_FAIL'

export const DETAIL_BERANDA_GALERI_REQUEST = 'DETAIL_BERANDA_GALERI_REQUEST'
export const DETAIL_BERANDA_GALERI_SUCCESS = 'DETAIL_BERANDA_GALERI_SUCCESS'
export const DETAIL_BERANDA_GALERI_FAIL = 'DETAIL_BERANDA_GALERI_FAIL'

export const KATEGORI_BERANDA_GALERI_REQUEST = 'KATEGORI_BERANDA_GALERI_REQUEST'
export const KATEGORI_BERANDA_GALERI_SUCCESS = 'KATEGORI_BERANDA_GALERI_SUCCESS'
export const KATEGORI_BERANDA_GALERI_FAIL = 'KATEGORI_BERANDA_GALERI_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'