export const DROPDOWN_HELPDESK_REQUEST = "DROPDOWN_HELPDESK_REQUEST";
export const DROPDOWN_HELPDESK_SUCCESS = "DROPDOWN_HELPDESK_SUCCESS";
export const DROPDOWN_HELPDESK_FAIL = "DROPDOWN_HELPDESK_FAIL";
