export const BERANDA_TESTIMONI_REQUEST = 'BERANDA_TESTIMONI_REQUEST'
export const BERANDA_TESTIMONI_SUCCESS = 'BERANDA_TESTIMONI_SUCCESS'
export const BERANDA_TESTIMONI_FAIL = 'BERANDA_TESTIMONI_FAIL'

export const DETAIL_BERANDA_TESTIMONI_REQUEST = 'DETAIL_BERANDA_TESTIMONI_REQUEST'
export const DETAIL_BERANDA_TESTIMONI_SUCCESS = 'DETAIL_BERANDA_TESTIMONI_SUCCESS'
export const DETAIL_BERANDA_TESTIMONI_FAIL = 'DETAIL_BERANDA_TESTIMONI_FAIL'

export const KATEGORI_BERANDA_TESTIMONI_REQUEST = 'KATEGORI_BERANDA_TESTIMONI_REQUEST'
export const KATEGORI_BERANDA_TESTIMONI_SUCCESS = 'KATEGORI_BERANDA_TESTIMONI_SUCCESS'
export const KATEGORI_BERANDA_TESTIMONI_FAIL = 'KATEGORI_BERANDA_TESTIMONI_FAIL'

export const CEK_LULUS_PELATIHAN_REQUEST = 'CEK_LULUS_PELATIHAN_REQUEST'
export const CEK_LULUS_PELATIHAN = 'CEK_LULUS_PELATIHAN'
export const CEK_LULUS_FAIL = 'CEK_LULUS_FAIL'

export const TAG_BERANDA_TESTIMONI_REQUEST = 'TAG_BERANDA_TESTIMONI_REQUEST'
export const TAG_BERANDA_TESTIMONI_SUCCESS = 'TAG_BERANDA_TESTIMONI_SUCCESS'
export const TAG_BERANDA_TESTIMONI_FAIL = 'TAG_BERANDA_TESTIMONI_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'