export const BERANDA_VIDEO_REQUEST = 'BERANDA_VIDEO_REQUEST'
export const BERANDA_VIDEO_SUCCESS = 'BERANDA_VIDEO_SUCCESS'
export const BERANDA_VIDEO_FAIL = 'BERANDA_VIDEO_FAIL'

export const DETAIL_BERANDA_VIDEO_REQUEST = 'DETAIL_BERANDA_VIDEO_REQUEST'
export const DETAIL_BERANDA_VIDEO_SUCCESS = 'DETAIL_BERANDA_VIDEO_SUCCESS'
export const DETAIL_BERANDA_VIDEO_FAIL = 'DETAIL_BERANDA_VIDEO_FAIL'

export const KATEGORI_BERANDA_VIDEO_REQUEST = 'KATEGORI_BERANDA_VIDEO_REQUEST'
export const KATEGORI_BERANDA_VIDEO_SUCCESS = 'KATEGORI_BERANDA_VIDEO_SUCCESS'
export const KATEGORI_BERANDA_VIDEO_FAIL = 'KATEGORI_BERANDA_VIDEO_FAIL'

export const TAG_BERANDA_VIDEO_REQUEST = 'TAG_BERANDA_VIDEO_REQUEST'
export const TAG_BERANDA_VIDEO_SUCCESS = 'TAG_BERANDA_VIDEO_SUCCESS'
export const TAG_BERANDA_VIDEO_FAIL = 'TAG_BERANDA_VIDEO_FAIL'

export const PLAY_BERANDA_VIDEO_REQUEST = 'PLAY_BERANDA_VIDEO_REQUEST'
export const PLAY_BERANDA_VIDEO_SUCCESS = 'PLAY_BERANDA_VIDEO_SUCCESS'
export const PLAY_BERANDA_VIDEO_FAIL = 'PLAY_BERANDA_VIDEO_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'